"""Generate frontend/lib/routes.dart from the Django URL conf.

Run from the repo root:  python frontend/tool/gen_routes.py

Every navigable Django page becomes one entry, so the Flutter app can reach
every template without hand-writing a screen per template.
"""
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "frontend" / "lib" / "routes.dart"

sys.path.insert(0, str(ROOT))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "hms.settings")

import django  # noqa: E402

django.setup()

from django.urls import get_resolver  # noqa: E402
from django.urls.resolvers import URLPattern, URLResolver  # noqa: E402

# Not user-facing screens: Django admin, JSON APIs, service worker, media/static.
SKIP_PREFIXES = (
    "admin/", "api/", "sw.js", "media/", "static/", "__debug__/", "__reload__/",
)


def walk(resolver, prefix="", namespace=""):
    for entry in resolver.url_patterns:
        route = prefix + str(entry.pattern)
        if isinstance(entry, URLResolver):
            ns = entry.namespace or namespace
            yield from walk(entry, route, ns)
        elif isinstance(entry, URLPattern):
            name = entry.name
            if not name:
                continue
            full_name = f"{namespace}:{name}" if namespace else name
            yield full_name, route, list(entry.pattern.regex.groupindex)


def clean(route):
    """`patient/<int:pk>/` -> `patient/<pk>/`; strip regex noise."""
    route = re.sub(r"<[^:>]+:([^>]+)>", r"<\1>", route)
    route = re.sub(r"\(\?P<([^>]+)>[^)]*\)", r"<\1>", route)
    return route.replace("^", "").replace("$", "")


def label(name):
    return name.split(":")[-1].replace("_", " ").title()


def dart_str(s):
    return "'" + s.replace("\\", r"\\").replace("'", r"\'") + "'"


def main():
    seen = set()
    rows = []
    for name, route, params in walk(get_resolver()):
        path = clean(route)
        if path.startswith(SKIP_PREFIXES) or path in seen:
            continue
        seen.add(path)
        module = path.split("/")[0] or "home"
        rows.append((name, "/" + path, module, params))

    rows.sort(key=lambda r: (r[2], r[0]))

    lines = [
        "// GENERATED by frontend/tool/gen_routes.py -- do not edit by hand.",
        "class HmsRoute {",
        "  final String name;",
        "  final String path;",
        "  final String module;",
        "  final List<String> params;",
        "  const HmsRoute(this.name, this.path, this.module, this.params);",
        "  String get label => name.split(':').last"
        ".replaceAll('_', ' ');",
        "}",
        "",
        "const hmsRoutes = <HmsRoute>[",
    ]
    for name, path, module, params in rows:
        p = ", ".join(dart_str(x) for x in params)
        lines.append(
            f"  HmsRoute({dart_str(name)}, {dart_str(path)}, "
            f"{dart_str(module)}, [{p}]),"
        )
    lines += ["];", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(rows)} routes -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
