# Generated by Django 5.2 on 2025-07-11 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('inpatient', '0005_admission_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inpatient.admission'),
        ),
    ]
