# Generated by Django 5.1.5 on 2025-08-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='source_app',
            field=models.CharField(blank=True, choices=[('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('appointment', 'Appointment'), ('theatre', 'Theatre'), ('billing', 'Billing/General'), ('other', 'Other')], default='billing', max_length=20, null=True),
        ),
    ]
