# Generated by Django 4.2.26 on 2025-11-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_payment_options_payment_idx_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.service'),
        ),
    ]
