# Generated by Django 4.2.26 on 2026-02-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoice_billing_inv_status_f2a322_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('insurance', 'Insurance'), ('wallet', 'Wallet'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('insurance', 'Insurance'), ('wallet', 'Wallet'), ('other', 'Other')], max_length=20),
        ),
    ]
