# Generated by Django 4.2.26 on 2026-06-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('add_bedchargeinvoice', 'Can create bed charge invoices'), ('view_bedchargeinvoice', 'Can view bed charge invoices'), ('add_consultationinvoice', 'Can create consultation invoices'), ('view_consultationinvoice', 'Can view consultation invoices'), ('add_feedingchargeinvoice', 'Can create feeding charge invoices'), ('view_feedingchargeinvoice', 'Can view feeding charge invoices'), ('add_inpatientinvoice', 'Can create inpatient invoices'), ('view_inpatientinvoice', 'Can view inpatient invoices'), ('add_labinvoice', 'Can create laboratory invoices'), ('view_labinvoice', 'Can view laboratory invoices'), ('add_nursingcareinvoice', 'Can create nursing care invoices'), ('view_nursingcareinvoice', 'Can view nursing care invoices'), ('add_pharmacyinvoice', 'Can create pharmacy invoices'), ('change_pharmacyinvoice', 'Can edit pharmacy invoices'), ('view_pharmacyinvoice', 'Can view pharmacy invoices'), ('add_radiologyinvoice', 'Can create radiology invoices'), ('view_radiologyinvoice', 'Can view radiology invoices'), ('add_theatreinvoice', 'Can create theatre invoices'), ('view_theatreinvoice', 'Can view theatre invoices'), ('cancel_invoice', 'Can cancel invoices'), ('create_all_invoices', 'Can create all invoice types'), ('delete_all_invoices', 'Can delete all invoice types'), ('edit_all_invoices', 'Can edit all invoice types'), ('view_all_invoices', 'Can view all invoice types'), ('email_invoice', 'Can email invoices'), ('print_invoice', 'Can print invoices')]},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'permissions': [('refund_payment', 'Can refund payments')]},
        ),
    ]
