# Generated by Django 4.2.26 on 2026-06-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_invoice_options_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='source_app',
            field=models.CharField(blank=True, choices=[('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('appointment', 'Appointment'), ('theatre', 'Theatre'), ('registration', 'Registration'), ('consultation', 'Consultation'), ('billing', 'Billing/General'), ('other', 'Other')], default='billing', max_length=20, null=True),
        ),
    ]
