# Generated by Django 4.2.26 on 2026-07-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_invoice_hospital_invoiceitem_hospital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'permissions': [('refund_payment', 'Can refund payments'), ('process_payment', 'Can process payments')]},
        ),
    ]
