# Generated by Django 4.2.26 on 2026-08-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'permissions': [('refund_payment', 'Can refund payments'), ('process_payment', 'Can process payments'), ('print_paymentreceipt', 'Can print payment receipts')]},
        ),
    ]
