# Generated by Django 5.2 on 2025-08-16 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_add_new_transaction_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_address', models.TextField()),
                ('recipient_department', models.CharField(blank=True, max_length=100, null=True)),
                ('mail_type', models.CharField(choices=[('letter', 'Letter'), ('package', 'Package'), ('document', 'Document'), ('other', 'Other')], max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='received', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mail', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_mail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meeting_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.CharField(max_length=200)),
                ('attendees_count', models.IntegerField()),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='desk_office.meetingroom')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='OfficeSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('stationery', 'Stationery'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('cleaning', 'Cleaning Supplies'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('received', 'Received'), ('issued', 'Issued'), ('damaged', 'Damaged'), ('returned', 'Returned')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_supplies', to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='desk_office.officesupply')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('visitor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('purpose', models.CharField(choices=[('consultation', 'Consultation'), ('meeting', 'Meeting'), ('delivery', 'Delivery'), ('other', 'Other')], max_length=20)),
                ('other_purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visitors', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
    ]
