# Generated by Django 5.2 on 2025-08-16 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_office', '0001_initial'),
        ('patients', '0006_add_new_transaction_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroom',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meetingroombooking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='meetingroombooking',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='officesupply',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplytransaction',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='supplytransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplytransaction',
            name='issued_to',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='patient',
        ),
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='MailItem',
        ),
        migrations.DeleteModel(
            name='MeetingRoom',
        ),
        migrations.DeleteModel(
            name='MeetingRoomBooking',
        ),
        migrations.DeleteModel(
            name='OfficeSupply',
        ),
        migrations.DeleteModel(
            name='SupplyTransaction',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
