# Generated by Django 5.2 on 2025-08-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_office', '0002_remove_meetingroom_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizationcode',
            name='service',
        ),
        migrations.AddField(
            model_name='authorizationcode',
            name='service_description',
            field=models.TextField(blank=True, help_text='Description of the specific service requested', null=True),
        ),
        migrations.AddField(
            model_name='authorizationcode',
            name='service_type',
            field=models.CharField(choices=[('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('theatre', 'Theatre/Surgery'), ('inpatient', 'Inpatient'), ('dental', 'Dental'), ('opthalmic', 'Ophthalmic'), ('ent', 'ENT'), ('oncology', 'Oncology'), ('gynae_emergency', 'Gynae Emergency'), ('labor', 'Labor & Delivery'), ('scbu', 'SCBU'), ('icu', 'ICU'), ('general', 'General Consultation'), ('other', 'Other Services')], default='general', max_length=50),
        ),
    ]
