# Generated by Django 4.2.7 on 2025-11-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_office', '0003_remove_authorizationcode_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcode',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount covered by this authorization', max_digits=10),
        ),
    ]
