# Generated by Django 4.2.7 on 2025-11-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_office', '0004_authorizationcode_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationcode',
            name='code',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
