# Generated by Django 4.2.26 on 2026-01-30 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0016_alter_patient_blood_group'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMedicineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chief_complaint', models.TextField(blank=True, help_text='Primary reason for visit', null=True)),
                ('history_of_present_illness', models.TextField(blank=True, null=True)),
                ('past_medical_history', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('social_history', models.TextField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Celsius', max_digits=4, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Breaths per minute', null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, help_text='SpO2 percentage', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in meters', max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index', max_digits=5, null=True)),
                ('general_appearance', models.TextField(blank=True, null=True)),
                ('cardiovascular_exam', models.TextField(blank=True, null=True)),
                ('respiratory_exam', models.TextField(blank=True, null=True)),
                ('gastrointestinal_exam', models.TextField(blank=True, null=True)),
                ('neurological_exam', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('authorization_code', models.CharField(blank=True, help_text='Authorization code from desk office', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_medicine_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'General Medicine Record',
                'verbose_name_plural': 'General Medicine Records',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneralMedicineClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text="Patient's description of symptoms, concerns, and history")),
                ('objective', models.TextField(help_text='Observable findings, examination results, and measurements')),
                ('assessment', models.TextField(help_text='Clinical assessment, diagnosis, and interpretation')),
                ('plan', models.TextField(help_text='Treatment plan, interventions, and follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_medicine_clinical_notes_created', to=settings.AUTH_USER_MODEL)),
                ('general_medicine_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='general_medicine.generalmedicinerecord')),
            ],
            options={
                'verbose_name': 'General Medicine Clinical Note',
                'verbose_name_plural': 'General Medicine Clinical Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
