# Generated by Django 4.2.26 on 2026-01-30 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0016_alter_patient_blood_group'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PediatricsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('age_category', models.CharField(blank=True, help_text='Infant, Toddler, Preschool, School-age, Adolescent', max_length=20, null=True)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Birth weight in kg', max_digits=4, null=True)),
                ('gestational_age', models.DecimalField(blank=True, decimal_places=1, help_text='Gestational age in weeks', max_digits=3, null=True)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Current weight in kg', max_digits=5, null=True)),
                ('current_height', models.DecimalField(blank=True, decimal_places=2, help_text='Current height in cm', max_digits=5, null=True)),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=2, help_text='Head circumference in cm', max_digits=5, null=True)),
                ('weight_for_age_percentile', models.IntegerField(blank=True, null=True)),
                ('height_for_age_percentile', models.IntegerField(blank=True, null=True)),
                ('weight_for_height_percentile', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Breaths per minute (age-appropriate)', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Beats per minute (age-appropriate)', null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='BP (if applicable)', max_length=20, null=True)),
                ('developmental_milestones', models.TextField(blank=True, null=True)),
                ('developmental_concerns', models.TextField(blank=True, null=True)),
                ('immunization_status', models.TextField(blank=True, null=True)),
                ('feeding_pattern', models.TextField(blank=True, null=True)),
                ('nutritional_status', models.CharField(blank=True, help_text='Normal, Underweight, Overweight, Obese', max_length=50, null=True)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('history_of_present_illness', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('authorization_code', models.CharField(blank=True, help_text='Authorization code from desk office', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pediatrics_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Pediatrics Record',
                'verbose_name_plural': 'Pediatrics Records',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='PediatricsClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text="Patient's description of symptoms, concerns, and history")),
                ('objective', models.TextField(help_text='Observable findings, examination results, and measurements')),
                ('assessment', models.TextField(help_text='Clinical assessment, diagnosis, and interpretation')),
                ('plan', models.TextField(help_text='Treatment plan, interventions, and follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pediatrics_clinical_notes_created', to=settings.AUTH_USER_MODEL)),
                ('pediatrics_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='pediatrics.pediatricsrecord')),
            ],
            options={
                'verbose_name': 'Pediatrics Clinical Note',
                'verbose_name_plural': 'Pediatrics Clinical Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
