# Generated by Django 5.2 on 2025-07-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_clinicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='billed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
