# Generated by Django 5.2 on 2025-07-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0004_admission_billed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
