# Generated by Django 4.2.26 on 2026-06-12 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inpatient', '0007_admission_authorization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='staff',
            field=models.ManyToManyField(blank=True, help_text='Staff (doctors/nurses) assigned to this ward who can accept ward referrals', related_name='assigned_wards', to=settings.AUTH_USER_MODEL),
        ),
    ]
