# Generated by Django 4.2.26 on 2026-06-12 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inpatient', '0008_ward_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='staff',
            field=models.ManyToManyField(blank=True, help_text='Physicians assigned to this ward who can admit/accept patients and ward referrals', related_name='assigned_wards', to=settings.AUTH_USER_MODEL),
        ),
    ]
