# Generated by Django 4.2.26 on 2026-07-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0010_admission_hospital_bed_hospital_bedtransfer_hospital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'permissions': [('discharge_patient', 'Can discharge inpatients')]},
        ),
    ]
