# Generated by Django 5.1.5 on 2025-08-29 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_internalnotification_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soapnote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Core SOAP Note', 'verbose_name_plural': 'Core SOAP Notes'},
        ),
        migrations.RemoveField(
            model_name='internalnotification',
            name='description',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalnotification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='internalnotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalnotification',
            name='title',
            field=models.CharField(default='Notification', max_length=200),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='internalnotification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='assessment',
            field=models.TextField(help_text='Clinical assessment and diagnosis'),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='objective',
            field=models.TextField(help_text='Observable findings and test results'),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='plan',
            field=models.TextField(help_text='Treatment plan and follow-up'),
        ),
        migrations.AlterField(
            model_name='soapnote',
            name='subjective',
            field=models.TextField(help_text="Patient's description of symptoms"),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='core_auditl_timesta_80074f_idx'),
        ),
        migrations.AddIndex(
            model_name='internalnotification',
            index=models.Index(fields=['user', 'is_read'], name='core_intern_user_id_b161d0_idx'),
        ),
        migrations.AddIndex(
            model_name='internalnotification',
            index=models.Index(fields=['created_at'], name='core_intern_created_3f81d0_idx'),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='core_auditlog',
        ),
        migrations.AlterModelTable(
            name='internalnotification',
            table='core_internalnotification',
        ),
        migrations.AlterModelTable(
            name='soapnote',
            table='core_soapnote',
        ),
    ]
