# Generated by Django 4.2.7 on 2025-11-14 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_role_users_alter_customuserprofile_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMSPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Permission name (e.g., 'view_dashboard')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable permission name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows')),
                ('category', models.CharField(choices=[('dashboard', 'Dashboard'), ('patient_management', 'Patient Management'), ('medical_records', 'Medical Records'), ('consultations', 'Consultations'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('appointments', 'Appointments'), ('inpatient', 'Inpatient'), ('billing', 'Billing'), ('reports', 'Reports'), ('administration', 'Administration'), ('sidebar', 'Sidebar Access'), ('features', 'Feature Access')], help_text='Category for organization', max_length=50)),
                ('codename', models.CharField(help_text="System identifier (e.g., 'view_dashboard')", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this permission is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HMS Permission',
                'verbose_name_plural': 'HMS Permissions',
                'db_table': 'core_hmspermission',
                'ordering': ['category', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='SidebarMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title in sidebar', max_length=100)),
                ('url_name', models.CharField(blank=True, help_text="Django URL name (e.g., 'dashboard:dashboard')", max_length=100)),
                ('url_path', models.CharField(blank=True, help_text='Static URL path if no URL name', max_length=200)),
                ('icon', models.CharField(default='fas fa-circle', help_text='Font Awesome icon class', max_length=50)),
                ('category', models.CharField(choices=[('main', 'Main Navigation'), ('patient_care', 'Patient Care'), ('medical_services', 'Medical Services'), ('administration', 'Administration')], default='main', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in menu')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this menu item is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item for dropdowns', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.sidebarmenuitem')),
                ('permission_required', models.ForeignKey(blank=True, help_text='Permission required to view this menu item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hmspermission')),
                ('required_roles', models.ManyToManyField(blank=True, help_text='Specific roles that can access this item', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Sidebar Menu Item',
                'verbose_name_plural': 'Sidebar Menu Items',
                'db_table': 'core_sidebarmenuitem',
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Feature flag name (e.g., 'enhanced_pharmacy_workflow')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable feature name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the feature')),
                ('feature_type', models.CharField(choices=[('module', 'Module'), ('view', 'View'), ('button', 'Button/Action'), ('field', 'Form Field'), ('report', 'Report')], help_text='Type of feature', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this feature is currently enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_required', models.ForeignKey(blank=True, help_text='Permission required to access this feature', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hmspermission')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'core_featureflag',
                'ordering': ['feature_type', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for direct permission assignment')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='core.hmspermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hms_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission Assignment',
                'verbose_name_plural': 'User Permission Assignments',
                'db_table': 'core_userpermissionassignment',
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='RolePermissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_roles', to='core.hmspermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hms_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role Permission Assignment',
                'verbose_name_plural': 'Role Permission Assignments',
                'db_table': 'core_rolepermissionassignment',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
