# Generated by Django 4.2.7 on 2025-11-16 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_role_users_alter_customuserprofile_is_active_and_more'),
        ('core', '0005_hmspermission_sidebarmenuitem_featureflag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('patients', 'Patient Management'), ('consultations', 'Consultations'), ('appointments', 'Appointments'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('billing', 'Billing'), ('inpatient', 'Inpatient'), ('reports', 'Reports'), ('accounts', 'User Management'), ('system', 'System Administration'), ('desk_office', 'Desk Office'), ('nhia', 'NHIA Management'), ('theatre', 'Theatre')], db_index=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission Group',
                'verbose_name_plural': 'Permission Groups',
                'db_table': 'core_permissiongroup',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UIPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(db_index=True, help_text='Unique identifier (e.g., "btn_create_patient", "modal_delete_user")', max_length=100, unique=True)),
                ('element_label', models.CharField(help_text='Human-readable name for this UI element', max_length=200)),
                ('element_type', models.CharField(choices=[('link', 'Link'), ('button', 'Button'), ('modal', 'Modal'), ('menu_item', 'Menu Item'), ('tab', 'Tab'), ('section', 'Section'), ('form_field', 'Form Field'), ('action', 'Action')], default='link', max_length=20)),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('patients', 'Patient Management'), ('consultations', 'Consultations'), ('appointments', 'Appointments'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('billing', 'Billing'), ('inpatient', 'Inpatient'), ('reports', 'Reports'), ('accounts', 'User Management'), ('system', 'System Administration'), ('desk_office', 'Desk Office'), ('nhia', 'NHIA Management'), ('theatre', 'Theatre')], db_index=True, help_text='Application module this element belongs to', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this element does', null=True)),
                ('url_pattern', models.CharField(blank=True, help_text='URL pattern this element links to (for navigation)', max_length=200, null=True)),
                ('icon_class', models.CharField(blank=True, help_text='CSS icon class (e.g., "fas fa-user")', max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enable/disable without deletion')),
                ('is_system', models.BooleanField(default=False, help_text='System elements cannot be deleted by users')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying in lists/menus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ui_permissions', to=settings.AUTH_USER_MODEL)),
                ('required_permissions', models.ManyToManyField(blank=True, help_text='Django permissions required to access this UI element', related_name='ui_elements', to='auth.permission')),
                ('required_roles', models.ManyToManyField(blank=True, help_text='Roles that can access this UI element', related_name='ui_elements', to='accounts.role')),
            ],
            options={
                'verbose_name': 'UI Permission',
                'verbose_name_plural': 'UI Permissions',
                'db_table': 'core_uipermission',
                'ordering': ['module', 'display_order', 'element_label'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rolepermissionassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolepermissionassignment',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='rolepermissionassignment',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='rolepermissionassignment',
            name='role',
        ),
        migrations.RemoveField(
            model_name='sidebarmenuitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='sidebarmenuitem',
            name='permission_required',
        ),
        migrations.RemoveField(
            model_name='sidebarmenuitem',
            name='required_roles',
        ),
        migrations.AlterUniqueTogether(
            name='userpermissionassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpermissionassignment',
            name='granted_by',
        ),
        migrations.RemoveField(
            model_name='userpermissionassignment',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userpermissionassignment',
            name='user',
        ),
        migrations.DeleteModel(
            name='FeatureFlag',
        ),
        migrations.DeleteModel(
            name='HMSPermission',
        ),
        migrations.DeleteModel(
            name='RolePermissionAssignment',
        ),
        migrations.DeleteModel(
            name='SidebarMenuItem',
        ),
        migrations.DeleteModel(
            name='UserPermissionAssignment',
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='ui_permissions',
            field=models.ManyToManyField(help_text='UI permissions in this group', related_name='permission_groups', to='core.uipermission'),
        ),
        migrations.AddIndex(
            model_name='uipermission',
            index=models.Index(fields=['element_id', 'is_active'], name='core_uiperm_element_5275da_idx'),
        ),
        migrations.AddIndex(
            model_name='uipermission',
            index=models.Index(fields=['module', 'element_type'], name='core_uiperm_module_4d58b8_idx'),
        ),
        migrations.AddIndex(
            model_name='uipermission',
            index=models.Index(fields=['is_active', 'module'], name='core_uiperm_is_acti_75278e_idx'),
        ),
    ]
