# Generated by Django 4.2.26 on 2026-06-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_permissiongroup_uipermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
