# Generated by Django 4.2.26 on 2026-06-14 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_remove_soapnote_assessment_remove_soapnote_objective_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('point_type', models.CharField(choices=[('reception', 'Reception'), ('records', 'Health Records'), ('triage', 'Triage'), ('billing', 'Billing/Cashier')], default='reception', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Physical location/desk label', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ManyToManyField(blank=True, help_text='Receptionists / records officers assigned to this point', related_name='service_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Point',
                'verbose_name_plural': 'Service Points',
                'ordering': ['point_type', 'name'],
            },
        ),
    ]
