# Generated by Django 4.2.26 on 2026-07-12 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_customuser_phone_number_and_more'),
        ('core', '0012_activitylog_hospital_auditlog_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepoint',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this point belongs to (blank = hospital-wide)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_points', to='accounts.department'),
        ),
    ]
