# Generated by Django 4.2.26 on 2025-12-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhia', '0003_authorizationcode_service'),
        ('ophthalmic', '0004_ophthalmicclinicalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ophthalmicrecord',
            name='authorization_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='not_required', help_text='Status of authorization for this ophthalmic record', max_length=20),
        ),
        migrations.AddField(
            model_name='ophthalmicrecord',
            name='requires_authorization',
            field=models.BooleanField(default=False, help_text='True if this NHIA patient ophthalmic record requires desk office authorization'),
        ),
        migrations.AlterField(
            model_name='ophthalmicrecord',
            name='authorization_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ophthalmic_records', to='nhia.authorizationcode'),
        ),
    ]
