# Generated by Django 4.2.26 on 2026-06-12 16:05

from django.db import migrations, models


def copy_soap_to_clerking(apps, schema_editor):
    from core.clinical_notes import migrate_soap_to_clerking
    migrate_soap_to_clerking(apps, 'ophthalmic', 'ophthalmicclinicalnote')


class Migration(migrations.Migration):

    dependencies = [
        ('ophthalmic', '0005_ophthalmicrecord_authorization_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='differential_diagnosis',
            field=models.TextField(blank=True, default='', help_text='Other diagnoses under consideration'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='drug_history_allergies',
            field=models.TextField(blank=True, default='', help_text='Current medications and known allergies'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='family_social_history',
            field=models.TextField(blank=True, default='', help_text='Family illnesses and social circumstances'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='general_examination',
            field=models.TextField(blank=True, default='', help_text='General condition and vital signs'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='history_of_presenting_complaint',
            field=models.TextField(blank=True, default='', help_text='Detailed history of the presenting complaint'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='investigations',
            field=models.TextField(blank=True, default='', help_text='Investigations requested and results'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='management_plan',
            field=models.TextField(blank=True, default='', help_text='Treatment, interventions and follow-up'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='past_medical_surgical_history',
            field=models.TextField(blank=True, default='', help_text='Previous illnesses, admissions and surgeries'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='presenting_complaint',
            field=models.TextField(blank=True, default='', help_text='Main complaint(s) and duration'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='provisional_diagnosis',
            field=models.TextField(blank=True, default='', help_text='Most likely diagnosis'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='review_of_systems',
            field=models.TextField(blank=True, default='', help_text='Systematic enquiry across body systems'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Brief case summary'),
        ),
        migrations.AddField(
            model_name='ophthalmicclinicalnote',
            name='systemic_examination',
            field=models.TextField(blank=True, default='', help_text='System-by-system examination findings'),
        ),
        migrations.RunPython(copy_soap_to_clerking, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='ophthalmicclinicalnote',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='ophthalmicclinicalnote',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='ophthalmicclinicalnote',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='ophthalmicclinicalnote',
            name='subjective',
        ),
    ]
