# Generated by Django 5.2 on 2025-08-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('nhia', '0002_authorizationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='authorization_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_requests', to='nhia.authorizationcode'),
        ),
    ]
