# Generated by Django 4.2.26 on 2026-02-16 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_testrequest_authorization_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
