# Generated by Django 4.2.26 on 2026-06-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_alter_testrequest_request_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-result_date', '-created_at'], 'permissions': [('add_labresult', 'Can enter laboratory results')]},
        ),
    ]
