# Generated by Django 4.2.26 on 2026-07-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_test_hospital_testcategory_hospital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-result_date', '-created_at'], 'permissions': [('add_labresult', 'Can enter laboratory results'), ('enter_testresults', 'Can enter/edit lab test results')]},
        ),
    ]
