# Generated by Django 4.2.26 on 2026-08-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_seed_lab_catalog_standard_investigations'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
