# Generated by Django 4.2.26 on 2025-11-25 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family_planning', '0002_family_planningrecord_authorization_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPlanningClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text="Patient's description of symptoms, concerns, and history")),
                ('objective', models.TextField(help_text='Observable findings, examination results, and measurements')),
                ('assessment', models.TextField(help_text='Clinical assessment, diagnosis, and interpretation')),
                ('plan', models.TextField(help_text='Treatment plan, interventions, and follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_planning_clinical_notes_created', to=settings.AUTH_USER_MODEL)),
                ('family_planning_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='family_planning.family_planningrecord')),
            ],
            options={
                'verbose_name': 'Family_Planning Clinical Note',
                'verbose_name_plural': 'Family_Planning Clinical Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
