# Generated by Django 4.2.26 on 2026-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_planning', '0003_familyplanningclinicalnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_planningrecord',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='family_planningrecord',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
