# Generated by Django 4.2.26 on 2026-06-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_planning', '0005_alter_family_planningrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family_planningrecord',
            options={'ordering': ['-visit_date'], 'permissions': [('view_familyplanningrecord', 'Can view family planning records'), ('add_familyplanningrecord', 'Can create family planning records'), ('change_familyplanningrecord', 'Can edit family planning records')], 'verbose_name': 'Family_planning Record', 'verbose_name_plural': 'Family_planning Records'},
        ),
    ]
