# Generated by Django 5.2 on 2025-08-26 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('dental', '0001_initial'),
        ('nhia', '0001_initial'),
        ('patients', '0006_add_new_transaction_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dental Service',
                'verbose_name_plural': 'Dental Services',
            },
        ),
        migrations.CreateModel(
            name='DentalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='dental.dentalrecord')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dental Prescription',
                'verbose_name_plural': 'Dental Prescriptions',
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='DentalXRay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray_type', models.CharField(choices=[('bitewing', 'Bitewing'), ('periapical', 'Periapical'), ('panoramic', 'Panoramic'), ('cephalometric', 'Cephalometric'), ('occlusal', 'Occlusal'), ('other', 'Other')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dental_xrays/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('dental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrays', to='dental.dentalrecord')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dental X-Ray',
                'verbose_name_plural': 'Dental X-Rays',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='tooth',
            field=models.CharField(blank=True, choices=[('11', 'Upper Right Central Incisor (11)'), ('12', 'Upper Right Lateral Incisor (12)'), ('13', 'Upper Right Canine (13)'), ('14', 'Upper Right First Premolar (14)'), ('15', 'Upper Right Second Premolar (15)'), ('16', 'Upper Right First Molar (16)'), ('17', 'Upper Right Second Molar (17)'), ('18', 'Upper Right Third Molar/Wisdom Tooth (18)'), ('21', 'Upper Left Central Incisor (21)'), ('22', 'Upper Left Lateral Incisor (22)'), ('23', 'Upper Left Canine (23)'), ('24', 'Upper Left First Premolar (24)'), ('25', 'Upper Left Second Premolar (25)'), ('26', 'Upper Left First Molar (26)'), ('27', 'Upper Left Second Molar (27)'), ('28', 'Upper Left Third Molar/Wisdom Tooth (28)'), ('31', 'Lower Left Central Incisor (31)'), ('32', 'Lower Left Lateral Incisor (32)'), ('33', 'Lower Left Canine (33)'), ('34', 'Lower Left First Premolar (34)'), ('35', 'Lower Left Second Premolar (35)'), ('36', 'Lower Left First Molar (36)'), ('37', 'Lower Left Second Molar (37)'), ('38', 'Lower Left Third Molar/Wisdom Tooth (38)'), ('41', 'Lower Right Central Incisor (41)'), ('42', 'Lower Right Lateral Incisor (42)'), ('43', 'Lower Right Canine (43)'), ('44', 'Lower Right First Premolar (44)'), ('45', 'Lower Right Second Premolar (45)'), ('46', 'Lower Right First Molar (46)'), ('47', 'Lower Right Second Molar (47)'), ('48', 'Lower Right Third Molar/Wisdom Tooth (48)'), ('all', 'All Teeth'), ('upper', 'All Upper Teeth'), ('lower', 'All Lower Teeth')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='diagnosis',
            field=models.TextField(help_text='Diagnosis or findings', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='treatment_procedure',
            field=models.TextField(help_text='Treatment procedure performed', default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='treatment_status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='appointment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='next_appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_record', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_records', to='dental.dentalservice'),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='authorization_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_records', to='nhia.authorizationcode'),
        ),
    ]