# Generated by Django 5.2 on 2025-08-28 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0002_dental_expansion'),
        ('patients', '0006_add_new_transaction_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dentalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dental Record', 'verbose_name_plural': 'Dental Records'},
        ),
        migrations.AlterField(
            model_name='dentalrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_records', to='patients.patient'),
        ),
    ]
