# Generated by Django 4.2.26 on 2025-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0004_dentalclinicalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalrecord',
            name='authorization_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='not_required', help_text='Status of authorization for this dental record', max_length=20),
        ),
        migrations.AddField(
            model_name='dentalrecord',
            name='requires_authorization',
            field=models.BooleanField(default=False, help_text='True if this NHIA patient dental record requires desk office authorization'),
        ),
    ]
