# Generated by Django 5.2 on 2025-08-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrecord',
            name='authorization_code',
            field=models.CharField(blank=True, help_text='Authorization code from desk office', max_length=50, null=True),
        ),
    ]
