# Generated by Django 5.2 on 2025-08-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0002_entrecord_authorization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrecord',
            name='chief_complaint',
            field=models.TextField(blank=True, help_text='Chief complaint from patient', null=True),
        ),
        migrations.AddField(
            model_name='entrecord',
            name='history_of_present_illness',
            field=models.TextField(blank=True, help_text='History of present illness', null=True),
        ),
    ]
