# Generated by Django 5.2 on 2025-08-16 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhia', '0001_initial'),
        ('patients', '0006_add_new_transaction_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique authorization code', max_length=50, unique=True)),
                ('service_type', models.CharField(choices=[('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('theatre', 'Theatre'), ('inpatient', 'Inpatient'), ('dental', 'Dental'), ('opthalmic', 'Opthalmic'), ('ent', 'ENT'), ('oncology', 'Oncology'), ('general', 'General')], help_text='Type of service this authorization code is for', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount covered by this authorization', max_digits=10)),
                ('expiry_date', models.DateField(help_text='Expiry date for this authorization code')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_for', models.TextField(blank=True, help_text='Reference to the service this code was used for', null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Authorization Code',
                'verbose_name_plural': 'Authorization Codes',
                'ordering': ['-generated_at'],
            },
        ),
    ]
