# Generated by Django 4.2.26 on 2025-11-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_payment_options_payment_idx_payment_date_and_more'),
        ('nhia', '0002_authorizationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcode',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Service this authorization is for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_codes', to='billing.service'),
        ),
    ]
