# Generated by Django 4.2.26 on 2026-06-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhia', '0003_authorizationcode_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhiapatient',
            options={'permissions': [('process_nhibilling', 'Can process NHIA billing')], 'verbose_name': 'NHIA Patient', 'verbose_name_plural': 'NHIA Patients'},
        ),
    ]
