# Generated by Django 4.2.26 on 2026-07-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhia', '0005_authorizationcode_hospital_nhiapatient_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationcode',
            name='service_type',
            field=models.CharField(choices=[('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('theatre', 'Theatre'), ('inpatient', 'Inpatient'), ('dental', 'Dental'), ('opthalmic', 'Opthalmic'), ('ent', 'ENT'), ('oncology', 'Oncology'), ('appointment', 'Appointment'), ('general', 'General')], help_text='Type of service this authorization code is for', max_length=50),
        ),
    ]
