# Generated by Django 4.2.26 on 2026-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_hospital_address_hospital_email_hospital_phone'),
        ('nhia', '0006_alter_authorizationcode_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationcode',
            name='code',
            field=models.CharField(help_text='Authorization code, unique per hospital', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='authorizationcode',
            unique_together={('hospital', 'code')},
        ),
        migrations.AddConstraint(
            model_name='authorizationcode',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', True)), fields=('code',), name='uniq_authorization_code_when_no_hospital'),
        ),
    ]
