# Generated by Django 4.2.26 on 2025-12-12 16:26

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0014_sharedwallet_remove_wallettransaction_wallet_and_more'),
        ('nhia', '0003_authorizationcode_service'),
        ('billing', '0006_alter_invoiceitem_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DermatologyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(blank=True, choices=[('acne', 'Acne'), ('eczema', 'Eczema'), ('psoriasis', 'Psoriasis'), ('dermatitis', 'Dermatitis'), ('skin_cancer', 'Skin Cancer'), ('infection', 'Skin Infection'), ('allergy', 'Skin Allergy'), ('rosacea', 'Rosacea'), ('moles', 'Moles & Birthmarks'), ('other', 'Other Skin Condition')], max_length=20, null=True)),
                ('diagnosis', models.TextField(help_text='Diagnosis or findings')),
                ('treatment_procedure', models.TextField(help_text='Treatment procedure performed')),
                ('treatment_status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_appointment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires_authorization', models.BooleanField(default=False, help_text='True if this NHIA patient dermatology record requires desk office authorization')),
                ('authorization_status', models.CharField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='not_required', help_text='Status of authorization for this dermatology record', max_length=20)),
                ('authorization_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dermatology_records', to='nhia.authorizationcode')),
                ('dermatologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dermatology_treatments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dermatology_record', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dermatology_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Dermatology Record',
                'verbose_name_plural': 'Dermatology Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DermatologyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dermatology Service',
                'verbose_name_plural': 'Dermatology Services',
            },
        ),
        migrations.CreateModel(
            name='DermatologyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('biopsy', 'Skin Biopsy'), ('patch_test', 'Patch Test'), ('culture', 'Skin Culture'), ('woods_lamp', "Wood's Lamp Examination"), ('dermatoscopy', 'Dermatoscopy'), ('blood_test', 'Blood Test'), ('allergy_test', 'Allergy Test'), ('other', 'Other')], max_length=30)),
                ('results', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('dermatology_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='dermatology.dermatologyrecord')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dermatology Test',
                'verbose_name_plural': 'Dermatology Tests',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='dermatologyrecord',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dermatology_records', to='dermatology.dermatologyservice'),
        ),
        migrations.CreateModel(
            name='DermatologyPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dermatology_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='dermatology.dermatologyrecord')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dermatology Prescription',
                'verbose_name_plural': 'Dermatology Prescriptions',
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='DermatologyClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text="Patient's description of symptoms, concerns, and history")),
                ('objective', models.TextField(help_text='Observable findings, examination results, and measurements')),
                ('assessment', models.TextField(help_text='Clinical assessment, diagnosis, and interpretation')),
                ('plan', models.TextField(help_text='Treatment plan, interventions, and follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dermatology_clinical_notes_created', to=settings.AUTH_USER_MODEL)),
                ('dermatology_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='dermatology.dermatologyrecord')),
            ],
            options={
                'verbose_name': 'Dermatology Clinical Note',
                'verbose_name_plural': 'Dermatology Clinical Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
