# Generated by Django 5.2.3 on 2025-06-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgicalteam',
            old_name='notes',
            new_name='usage_notes',
        ),
    ]
