# Generated by Django 5.2 on 2025-06-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_surgerylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalequipment',
            name='calibration_frequency',
            field=models.DurationField(blank=True, help_text="e.g., '365 00:00:00' for annual calibration", null=True),
        ),
        migrations.AddField(
            model_name='surgicalequipment',
            name='last_calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
