# Generated by Django 5.2 on 2025-08-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhia', '0002_authorizationcode'),
        ('theatre', '0005_surgicalequipment_calibration_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='authorization_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='nhia.authorizationcode'),
        ),
    ]
