# Generated by Django 5.1.5 on 2025-08-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_source_app'),
        ('theatre', '0006_surgery_authorization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_invoices', to='billing.invoice'),
        ),
    ]
