# Generated by Django 5.2 on 2025-10-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0007_surgery_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgerytype',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Surgery fee in Naira (₦)', max_digits=10),
        ),
    ]
