# Generated by Django 5.1.5 on 2025-10-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhia', '0002_authorizationcode'),
        ('theatre', '0008_surgerytype_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='authorization_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='not_required', help_text='Status of authorization for this surgery', max_length=20),
        ),
        migrations.AddField(
            model_name='surgery',
            name='requires_authorization',
            field=models.BooleanField(default=False, help_text='True if this NHIA patient surgery requires desk office authorization'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='authorization_code',
            field=models.ForeignKey(blank=True, help_text='Authorization code from desk office for NHIA patient surgery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='nhia.authorizationcode'),
        ),
    ]
