# Generated by Django 5.2 on 2026-02-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0009_add_authorization_fields_to_surgery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryTypeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField(default=1, help_text='Quantity of this equipment needed for the surgery')),
                ('is_mandatory', models.BooleanField(default=True, help_text='If true, this equipment must be available for the surgery to proceed')),
                ('notes', models.TextField(blank=True, help_text='Special instructions for using this equipment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_types_required', to='theatre.surgicalequipment')),
                ('surgery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_equipment', to='theatre.surgerytype')),
            ],
            options={
                'verbose_name': 'Surgery Type Equipment Requirement',
                'verbose_name_plural': 'Surgery Type Equipment Requirements',
                'ordering': ['surgery_type', 'equipment__name'],
                'unique_together': {('surgery_type', 'equipment')},
            },
        ),
    ]
