# Generated by Django 5.2 on 2026-02-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0010_surgerytypeequipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('maintenance', 'Routine Maintenance'), ('calibration', 'Calibration'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('replacement', 'Part Replacement'), ('upgrade', 'Upgrade/Modification'), ('cleaning', 'Deep Cleaning')], default='maintenance', max_length=20)),
                ('scheduled_date', models.DateField(help_text='When maintenance is scheduled')),
                ('completed_date', models.DateField(blank=True, help_text='When maintenance was actually completed', null=True)),
                ('next_due_date', models.DateField(blank=True, help_text='When next maintenance is due', null=True)),
                ('description', models.TextField(help_text='Description of work performed or to be performed')),
                ('findings', models.TextField(blank=True, help_text='Findings during maintenance', null=True)),
                ('parts_replaced', models.TextField(blank=True, help_text='Parts that were replaced', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of maintenance (₦)', max_digits=10, null=True)),
                ('external_provider', models.CharField(blank=True, help_text='External service company', max_length=200, null=True)),
                ('external_technician', models.CharField(blank=True, help_text='Technician name', max_length=200, null=True)),
                ('certificate_number', models.CharField(blank=True, help_text='Calibration certificate number', max_length=100, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='maintenance_docs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_logs', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='theatre.surgicalequipment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Maintenance Log',
                'verbose_name_plural': 'Equipment Maintenance Logs',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
    ]
