# Generated by Django 4.2.26 on 2026-02-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0011_equipmentmaintenancelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed'), ('pending', 'Pending')], default='scheduled', max_length=20),
        ),
    ]
