# Generated by Django 4.2.26 on 2026-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0012_alter_surgery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmaintenancelog',
            name='completed_date',
            field=models.DateTimeField(blank=True, help_text='When maintenance was actually completed', null=True),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenancelog',
            name='next_due_date',
            field=models.DateTimeField(blank=True, help_text='When next maintenance is due', null=True),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenancelog',
            name='scheduled_date',
            field=models.DateTimeField(help_text='When maintenance is scheduled'),
        ),
        migrations.AlterField(
            model_name='surgicalequipment',
            name='last_calibration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgicalequipment',
            name='last_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgicalequipment',
            name='next_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
