# Generated by Django 4.2.26 on 2026-06-10 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0011_alter_referral_referral_type'),
        ('theatre', '0013_alter_equipmentmaintenancelog_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='source_referral',
            field=models.ForeignKey(blank=True, help_text='Referral that this surgery was scheduled from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='consultations.referral'),
        ),
    ]
