# Generated by Django 4.2.26 on 2026-06-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('theatre', '0015_seed_surgery_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmaintenancelog',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='operationtheatre',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='postoperativenote',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='preoperativechecklist',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='surgerylog',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='surgerytype',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='surgerytypeequipment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='surgicalequipment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='surgicalteam',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
    ]
