# Generated by Django 4.2.26 on 2026-07-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_enforce_annual_discount'),
        ('theatre', '0016_equipmentmaintenancelog_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtheatre',
            name='theatre_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='operationtheatre',
            unique_together={('hospital', 'theatre_number')},
        ),
    ]
