# Generated by Django 4.2.26 on 2026-07-07 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_enforce_annual_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theatre', '0017_alter_operationtheatre_theatre_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgicalTeamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital')),
            ],
            options={
                'verbose_name': 'Surgical Team Template',
                'verbose_name_plural': 'Surgical Team Templates',
                'ordering': ['name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SurgicalTeamTemplateMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('surgeon', 'Surgeon'), ('assistant_surgeon', 'Assistant Surgeon'), ('anesthetist', 'Anesthetist'), ('nurse', 'Nurse'), ('technician', 'Technician'), ('other', 'Other')], max_length=20)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_template_memberships', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='theatre.surgicalteamtemplate')),
            ],
            options={
                'unique_together': {('template', 'staff', 'role')},
            },
        ),
    ]
