# Generated by Django 4.2.26 on 2026-07-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0018_surgicalteamtemplate_surgicalteamtemplatemember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surgicalteamtemplatemember',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='surgicalteamtemplatemember',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Display order within the team'),
        ),
    ]
