# Generated by Django 4.2.26 on 2026-08-21 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0019_alter_surgicalteamtemplatemember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmaintenancelog',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'csv', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tif', 'tiff', 'webp'])]),
        ),
    ]
