# Generated by Django 5.2 on 2025-07-01 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medicationinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensinglog',
            name='dispensary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_logs', to='pharmacy.dispensary'),
        ),
    ]
