# Generated by Django 5.2 on 2025-07-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_dispensinglog_dispensary'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='medication',
            name='pharmacy_me_stock_q_83487e_idx',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='stock_quantity',
        ),
    ]
