# Generated by Django 5.2 on 2025-07-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_remove_medication_pharmacy_me_stock_q_83487e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='dispensary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='pharmacy.dispensary'),
        ),
    ]
