# Generated by Django 5.1.5 on 2025-08-11 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_purchase_dispensary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=1000, help_text='Maximum number of medication units this store can hold')),
                ('temperature_controlled', models.BooleanField(default=False)),
                ('humidity_controlled', models.BooleanField(default=False)),
                ('security_level', models.CharField(choices=[('basic', 'Basic'), ('medium', 'Medium'), ('high', 'High'), ('maximum', 'Maximum')], default='basic', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_store', to='pharmacy.dispensary')),
            ],
            options={
                'verbose_name': 'Active Store',
                'verbose_name_plural': 'Active Stores',
                'ordering': ['dispensary__name'],
            },
        ),
        migrations.CreateModel(
            name='BulkStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=10000, help_text='Maximum number of medication units this bulk store can hold')),
                ('temperature_controlled', models.BooleanField(default=True)),
                ('humidity_controlled', models.BooleanField(default=True)),
                ('security_level', models.CharField(choices=[('basic', 'Basic'), ('medium', 'Medium'), ('high', 'High'), ('maximum', 'Maximum')], default='high', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_bulk_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Store',
                'verbose_name_plural': 'Bulk Stores',
                'ordering': ['name'],
            },
        ),
    ]
