# Generated by Django 5.1.5 on 2025-08-11 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_activestore_bulkstore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationinventory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='medicationinventory',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='MedicationTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_bulk_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='pharmacy.bulkstore')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='pharmacy.medication')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_active_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='pharmacy.activestore')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medication Transfer',
                'verbose_name_plural': 'Medication Transfers',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveStoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_restock_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_stocks', to='pharmacy.activestore')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_store_inventories', to='pharmacy.medication')),
            ],
            options={
                'verbose_name': 'Active Store Inventory',
                'verbose_name_plural': 'Active Store Inventories',
                'ordering': ['active_store__dispensary__name', 'medication__name'],
                'unique_together': {('medication', 'active_store', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='BulkStoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('last_transfer_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulk_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_stocks', to='pharmacy.bulkstore')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_store_inventories', to='pharmacy.medication')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.supplier')),
            ],
            options={
                'verbose_name': 'Bulk Store Inventory',
                'verbose_name_plural': 'Bulk Store Inventories',
                'ordering': ['bulk_store__name', 'medication__name'],
                'unique_together': {('medication', 'bulk_store', 'batch_number')},
            },
        ),
    ]
