# Generated by Django 4.2.7 on 2025-11-06 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy_billing', '0003_payment'),
        ('consultations', '0010_remove_consultation_consultation_type_and_more'),
        ('nhia', '0002_authorizationcode'),
        ('pharmacy', '0009_medicalpack_packitem_packorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensaryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterDispensaryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inter-Dispensary Transfer',
                'verbose_name_plural': 'Inter-Dispensary Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_type', models.CharField(choices=[('medication', 'Medication'), ('supply', 'Medical Supply'), ('equipment', 'Equipment')], default='medication', max_length=20)),
                ('usage_instructions', models.TextField(blank=True, help_text='Instructions for using this item', null=True)),
                ('is_critical', models.BooleanField(default=False, help_text='Critical items cannot be substituted')),
                ('is_optional', models.BooleanField(default=False, help_text='Optional items can be omitted if unavailable')),
                ('order', models.IntegerField(default=0, help_text='Order of usage in procedure (0 for no specific order)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medical Pack Item',
                'verbose_name_plural': 'Medical Pack Items',
                'ordering': ['order', 'medication__name'],
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('partially_dispensed', 'Partially Dispensed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription Cart',
                'verbose_name_plural': 'Prescription Carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Total quantity to dispense/bill')),
                ('quantity_dispensed', models.IntegerField(default=0, help_text='Quantity already dispensed from this cart item')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of adding to cart', max_digits=10)),
                ('available_stock', models.IntegerField(default=0, help_text='Available stock at time of adding to cart (cached)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='activestore',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='activestoreinventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bulkstore',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='bulkstoreinventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dispensinglog',
            options={'ordering': ['-dispensed_date'], 'verbose_name': 'Dispensing Log', 'verbose_name_plural': 'Dispensing Logs'},
        ),
        migrations.AlterModelOptions(
            name='medicalpack',
            options={'ordering': ['name'], 'verbose_name': 'Medical Pack', 'verbose_name_plural': 'Medical Packs'},
        ),
        migrations.AlterModelOptions(
            name='medicationtransfer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-prescription_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_purchases', 'Can approve purchase orders'), ('can_process_payments', 'Can process purchase payments')]},
        ),
        migrations.RemoveIndex(
            model_name='medicalpack',
            name='pharmacy_me_pack_ty_fb364d_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicalpack',
            name='pharmacy_me_surgery_9a2880_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicalpack',
            name='pharmacy_me_labor_t_320687_idx',
        ),
        migrations.RemoveIndex(
            model_name='medicalpack',
            name='pharmacy_me_is_acti_5b9413_idx',
        ),
        migrations.RemoveIndex(
            model_name='packorder',
            name='pharmacy_pa_status_5871ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='packorder',
            name='pharmacy_pa_order_d_004011_idx',
        ),
        migrations.RemoveIndex(
            model_name='packorder',
            name='pharmacy_pa_schedul_daf2b5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='activestoreinventory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bulkstoreinventory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='packitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bulkstore',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='medicalpack',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='medicalpack',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='dispensed_at',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='dispensed_by',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='processing_notes',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='dispensed_by',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='dispensed_date',
        ),
        migrations.AddField(
            model_name='medicationtransfer',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationtransfer',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packorder',
            name='ordered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='authorization_code',
            field=models.ForeignKey(blank=True, help_text='Authorization code from desk office for NHIA patient prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='nhia.authorizationcode'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='authorization_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='not_required', help_text='Status of authorization for this prescription', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(blank=True, help_text='Link to the consultation this prescription was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='requires_authorization',
            field=models.BooleanField(default=False, help_text='True if this NHIA patient prescription from non-NHIA consultation requires desk office authorization'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='priority_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='submitted_for_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activestore',
            name='capacity',
            field=models.IntegerField(help_text='Maximum storage capacity in units'),
        ),
        migrations.AlterField(
            model_name='activestore',
            name='security_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('medium', 'Medium'), ('high', 'High')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='activestoreinventory',
            name='active_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='pharmacy.activestore'),
        ),
        migrations.AlterField(
            model_name='activestoreinventory',
            name='batch_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activestoreinventory',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activestoreinventory',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_inventories', to='pharmacy.medication'),
        ),
        migrations.AlterField(
            model_name='activestoreinventory',
            name='reorder_level',
            field=models.IntegerField(default=10, help_text='Minimum stock level before reorder is needed'),
        ),
        migrations.AlterField(
            model_name='bulkstore',
            name='capacity',
            field=models.IntegerField(help_text='Maximum storage capacity in units'),
        ),
        migrations.AlterField(
            model_name='bulkstore',
            name='humidity_controlled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bulkstore',
            name='security_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('medium', 'Medium'), ('high', 'High')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkstore',
            name='temperature_controlled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bulkstoreinventory',
            name='batch_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bulkstoreinventory',
            name='bulk_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='pharmacy.bulkstore'),
        ),
        migrations.AlterField(
            model_name='bulkstoreinventory',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bulkstoreinventory',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_inventories', to='pharmacy.medication'),
        ),
        migrations.AlterField(
            model_name='bulkstoreinventory',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicalpack',
            name='labor_type',
            field=models.CharField(blank=True, choices=[('normal_delivery', 'Normal Delivery'), ('assisted_delivery', 'Assisted Delivery'), ('cesarean_section', 'Cesarean Section')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicalpack',
            name='pack_type',
            field=models.CharField(choices=[('surgery', 'Surgery'), ('labor', 'Labor/Delivery'), ('emergency', 'Emergency'), ('routine', 'Routine Care')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalpack',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Check if this pack requires approval before processing'),
        ),
        migrations.AlterField(
            model_name='medicalpack',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalpack',
            name='surgery_type',
            field=models.CharField(blank=True, choices=[('appendectomy', 'Appendectomy'), ('cholecystectomy', 'Cholecystectomy'), ('hernia_repair', 'Hernia Repair'), ('cesarean_section', 'Cesarean Section'), ('tonsillectomy', 'Tonsillectomy')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicationtransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='packitem',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Critical items cannot be substituted'),
        ),
        migrations.AlterField(
            model_name='packitem',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Optional items can be omitted if unavailable'),
        ),
        migrations.AlterField(
            model_name='packitem',
            name='item_type',
            field=models.CharField(choices=[('medication', 'Medication'), ('supply', 'Medical Supply'), ('equipment', 'Equipment')], default='medication', max_length=20),
        ),
        migrations.AlterField(
            model_name='packitem',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of usage in procedure (0 for no specific order)'),
        ),
        migrations.AlterField(
            model_name='packitem',
            name='usage_instructions',
            field=models.TextField(blank=True, help_text='Instructions for using this item', null=True),
        ),
        migrations.AlterField(
            model_name='packorder',
            name='order_notes',
            field=models.TextField(blank=True, help_text='Additional notes about this pack order', null=True),
        ),
        migrations.AlterField(
            model_name='packorder',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_pack_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packorder',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicalpack'),
        ),
        migrations.AlterField(
            model_name='packorder',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_pack_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('cancelled', 'Cancelled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(blank=True, help_text='Dosage instructions (e.g., 500mg, 10ml)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(blank=True, help_text='How long to take (e.g., 7 days, 2 weeks)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(blank=True, help_text='How often to take (e.g., twice daily, once daily)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='instructions',
            field=models.TextField(blank=True, help_text='Special instructions for taking the medication', null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity to dispense (managed at cart level)'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient'], name='idx_presc_patient'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor'], name='idx_presc_doctor'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='idx_presc_status'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_date'], name='idx_presc_date'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['payment_status'], name='idx_presc_payment'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['authorization_status'], name='idx_presc_auth'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['created_at'], name='idx_presc_created'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pharmacy.purchase'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptioncartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescriptioncart'),
        ),
        migrations.AddField(
            model_name='prescriptioncartitem',
            name='prescription_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pharmacy.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='prescriptioncart',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_carts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptioncart',
            name='dispensary',
            field=models.ForeignKey(blank=True, help_text='Dispensary from which items will be dispensed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.dispensary'),
        ),
        migrations.AddField(
            model_name='prescriptioncart',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_cart', to='pharmacy_billing.invoice'),
        ),
        migrations.AddField(
            model_name='prescriptioncart',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='pharmacy.prescription'),
        ),
        migrations.AddField(
            model_name='pack',
            name='medications',
            field=models.ManyToManyField(through='pharmacy.PackItem', to='pharmacy.medication'),
        ),
        migrations.AddField(
            model_name='medicalpackitem',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medication'),
        ),
        migrations.AddField(
            model_name='medicalpackitem',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.medicalpack'),
        ),
        migrations.AddField(
            model_name='interdispensarytransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inter_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interdispensarytransfer',
            name='from_dispensary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_inter_transfers', to='pharmacy.dispensary'),
        ),
        migrations.AddField(
            model_name='interdispensarytransfer',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_dispensary_transfers', to='pharmacy.medication'),
        ),
        migrations.AddField(
            model_name='interdispensarytransfer',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_inter_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interdispensarytransfer',
            name='to_dispensary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_inter_transfers', to='pharmacy.dispensary'),
        ),
        migrations.AddField(
            model_name='interdispensarytransfer',
            name='transferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_inter_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensarytransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dispensary_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensarytransfer',
            name='from_active_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dispensary_transfers', to='pharmacy.activestore'),
        ),
        migrations.AddField(
            model_name='dispensarytransfer',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_transfers', to='pharmacy.medication'),
        ),
        migrations.AddField(
            model_name='dispensarytransfer',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_dispensary_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispensarytransfer',
            name='to_dispensary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dispensary_transfers', to='pharmacy.dispensary'),
        ),
        migrations.AddField(
            model_name='dispensarytransfer',
            name='transferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_dispensary_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='bulkstoreinventory',
            name='last_transfer_date',
        ),
        migrations.AlterField(
            model_name='packitem',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pack'),
        ),
        migrations.AlterUniqueTogether(
            name='prescriptioncartitem',
            unique_together={('cart', 'prescription_item')},
        ),
        migrations.AlterUniqueTogether(
            name='medicalpackitem',
            unique_together={('pack', 'medication')},
        ),
        migrations.AddIndex(
            model_name='interdispensarytransfer',
            index=models.Index(fields=['status', '-created_at'], name='pharmacy_in_status_80d5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='interdispensarytransfer',
            index=models.Index(fields=['from_dispensary', 'status'], name='pharmacy_in_from_di_fb67de_idx'),
        ),
        migrations.AddIndex(
            model_name='interdispensarytransfer',
            index=models.Index(fields=['to_dispensary', 'status'], name='pharmacy_in_to_disp_eb9a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='interdispensarytransfer',
            index=models.Index(fields=['medication', 'status'], name='pharmacy_in_medicat_89cd37_idx'),
        ),
    ]
