# Generated by Django 4.2.7 on 2025-11-07 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0010_dispensarytransfer_interdispensarytransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptioncartitem',
            name='substitute_medication',
            field=models.ForeignKey(blank=True, help_text='Alternative medication to be dispensed instead of prescribed medication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_in_carts', to='pharmacy.medication'),
        ),
        migrations.AddField(
            model_name='prescriptioncartitem',
            name='substitute_reason',
            field=models.TextField(blank=True, help_text='Reason for medication substitution', null=True),
        ),
        migrations.AddField(
            model_name='prescriptioncartitem',
            name='substituted_at',
            field=models.DateTimeField(blank=True, help_text='When the substitution was made', null=True),
        ),
        migrations.AddField(
            model_name='prescriptioncartitem',
            name='substituted_by',
            field=models.ForeignKey(blank=True, help_text='User who authorized the substitution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_substitutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
