# Generated by Django 5.2 on 20250828 18:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_auto_20250828_1753'),
    ]

    operations = [
        # This migration is now empty as the field was added in the previous migration
        # migrations.AddField(
        #     model_name='activestoreinventory',
        #     name='last_restock_date',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
    ]