# Generated by Django 4.2.26 on 2025-11-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhia', '0003_authorizationcode_service'),
        ('pharmacy', '0011_prescriptioncartitem_substitute_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packorder',
            name='authorization_code',
            field=models.ForeignKey(blank=True, help_text='Authorization code for NHIA patients', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_orders', to='nhia.authorizationcode'),
        ),
    ]
