# Generated by Django 5.2 on 2025-08-28 21:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_activestoreinventory_last_restock_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='packitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packorder',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='packorder',
            name='pharmacy_pa_status_5871ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='packorder',
            name='pharmacy_pa_order_d_004011_idx',
        ),
        migrations.RemoveIndex(
            model_name='packorder',
            name='pharmacy_pa_schedul_daf2b5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='packitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='dispensed_at',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='dispensed_by',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='labor_record',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='processing_notes',
        ),
        migrations.RemoveField(
            model_name='packorder',
            name='surgery',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='dispensed_by',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='dispensed_date',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='quantity_dispensed_so_far',
        ),
        migrations.AddField(
            model_name='activestoreinventory',
            name='reorder_level',
            field=models.IntegerField(default=10, help_text='Minimum stock level before reorder is needed'),
        ),
        migrations.AddField(
            model_name='packorder',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packitem',
            name='item_type',
            field=models.CharField(choices=[('medication', 'Medication'), ('supply', 'Medical Supply'), ('equipment', 'Equipment')], default='medication', max_length=20),
        ),
        migrations.AlterField(
            model_name='packorder',
            name='ordered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_pack_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packorder',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_pack_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('cancelled', 'Cancelled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pack',
            name='medications',
            field=models.ManyToManyField(through='pharmacy.PackItem', to='pharmacy.medication'),
        ),
        migrations.AlterField(
            model_name='packitem',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.pack'),
        ),
        migrations.AlterField(
            model_name='packorder',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pack'),
        ),
    ]
