# Generated by Django 4.2.26 on 2025-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_packorder_authorization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
