# Generated by Django 5.2 on 2025-08-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_rename_dispensed_date_to_dispensed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='quantity_dispensed_so_far',
            field=models.IntegerField(default=0),
        ),
    ]