# Generated by Django 4.2.26 on 2025-11-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_make_invoice_number_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkstoreinventory',
            name='marked_up_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost after markup applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='bulkstoreinventory',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='Markup percentage (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='activestoreinventory',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Latest batch number (for display only)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activestoreinventory',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Earliest expiry date (from FIFO)', null=True),
        ),
        migrations.AlterField(
            model_name='activestoreinventory',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Total quantity across all batches'),
        ),
        migrations.AlterField(
            model_name='activestoreinventory',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weighted average cost', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='activestoreinventory',
            unique_together={('medication', 'active_store')},
        ),
        migrations.CreateModel(
            name='ActiveStoreBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.activestoreinventory')),
            ],
            options={
                'ordering': ['expiry_date', 'received_date'],
                'unique_together': {('active_inventory', 'batch_number')},
            },
        ),
    ]
