# Generated by Django 5.1.5 on 2025-08-30 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_add_quantity_dispensed_so_far'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_type', models.CharField(choices=[('medication', 'Medication'), ('supply', 'Medical Supply'), ('equipment', 'Equipment')], default='medication', max_length=20)),
                ('usage_instructions', models.TextField(blank=True, help_text='Instructions for using this item', null=True)),
                ('is_critical', models.BooleanField(default=False, help_text='Critical items cannot be substituted')),
                ('is_optional', models.BooleanField(default=False, help_text='Optional items can be omitted if unavailable')),
                ('order', models.IntegerField(default=0, help_text='Order of usage in procedure (0 for no specific order)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medication')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.medicalpack')),
            ],
            options={
                'verbose_name': 'Medical Pack Item',
                'verbose_name_plural': 'Medical Pack Items',
                'ordering': ['order', 'medication__name'],
                'unique_together': {('pack', 'medication')},
            },
        ),
    ]
