# Generated by Django 5.1.5 on 2025-08-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_medicalpackitem'),
    ]

    operations = [
    ]
