# Generated by Django 4.2.26 on 2025-11-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_create_active_store_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkstoreinventory',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Markup percentage (0-100)', max_digits=5),
        ),
    ]
