# Generated by Django 5.1.5 on 2025-08-31 12:37

import django.db.models.deletion
from django.db import migrations, models
from django.db.utils import OperationalError


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0017_fix_packorder_field_name'),
        ('theatre', '0007_surgery_invoice'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT 1;",  # Dummy SQL, we'll handle the actual operation in the reverse_sql
            reverse_sql="""
                ALTER TABLE pharmacy_packorder ADD COLUMN surgery_id INTEGER REFERENCES theatre_surgery(id);
                CREATE INDEX IF NOT EXISTS pharmacy_packorder_surgery_id_idx ON pharmacy_packorder(surgery_id);
            """,
            state_operations=[
                migrations.AddField(
                    model_name='packorder',
                    name='surgery',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_orders', to='theatre.surgery'),
                ),
            ]
        )
    ]