# Generated by Django 4.2.26 on 2026-01-16 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0018_update_existing_markup_to_20'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacistDispensaryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date when pharmacist was assigned to this dispensary')),
                ('end_date', models.DateField(blank=True, help_text='Date when assignment ended (if the pharmacist stopped working here)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispensary', models.ForeignKey(help_text='The dispensary where the pharmacist is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_assignments', to='pharmacy.dispensary')),
                ('pharmacist', models.ForeignKey(help_text='The pharmacist user', on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacist Dispensary Assignment',
                'verbose_name_plural': 'Pharmacist Dispensary Assignments',
                'ordering': ['-start_date', 'dispensary__name'],
                'unique_together': {('pharmacist', 'dispensary')},
            },
        ),
        migrations.AddField(
            model_name='dispensary',
            name='pharmacists',
            field=models.ManyToManyField(blank=True, help_text='Pharmacists assigned to this dispensary with their access permissions', related_name='pharmacist_dispensaries', through='pharmacy.PharmacistDispensaryAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
