# Generated by Django 5.2.6 on 2025-09-30 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_authorization_code_and_more'),
        ('nhia', '0002_authorizationcode'),
        ('pharmacy', '0018_add_surgery_field_to_packorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='authorization_code',
            field=models.ForeignKey(blank=True, help_text='Authorization code from desk office for NHIA patient prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='nhia.authorizationcode'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='authorization_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='not_required', help_text='Status of authorization for this prescription', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(blank=True, help_text='Link to the consultation this prescription was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='requires_authorization',
            field=models.BooleanField(default=False, help_text='True if this NHIA patient prescription from non-NHIA consultation requires desk office authorization'),
        ),
        migrations.AlterField(
            model_name='packorder',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicalpack'),
        ),
    ]
