# Generated by Django 4.2.26 on 2026-01-28 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0019_pharmacistdispensaryassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pack_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packorder',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packorder',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_pack_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packorder',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_order', to='pharmacy.prescription'),
        ),
        migrations.AddField(
            model_name='packorder',
            name='processing_notes',
            field=models.TextField(blank=True, help_text='Notes about order processing', null=True),
        ),
    ]
