# Generated by Django 4.2.26 on 2026-02-16 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0020_packorder_approved_at_packorder_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkstoreinventory',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pharmacistdispensaryassignment',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date when assignment ended (if the pharmacist stopped working here)', null=True),
        ),
        migrations.AlterField(
            model_name='pharmacistdispensaryassignment',
            name='start_date',
            field=models.DateTimeField(help_text='Date when pharmacist was assigned to this dispensary'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='expected_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
