# Generated by Django 4.2.26 on 2026-06-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0023_add_manager_to_bulkstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
    ]
