# Generated by Django 5.2 on 2025-10-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0023_partial_dispensing_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptioncartitem',
            name='quantity',
            field=models.IntegerField(help_text='Total quantity to dispense/bill'),
        ),
    ]
