# Generated by Django 4.2.26 on 2026-06-12 06:51

from django.db import migrations, models


def mark_approved_purchases_received(apps, schema_editor):
    """Under the old flow, stock was added to inventory at approval time.
    Mark already-approved purchases as fully received so the new receive
    action cannot add their stock a second time."""
    Purchase = apps.get_model("pharmacy", "Purchase")
    PurchaseItem = apps.get_model("pharmacy", "PurchaseItem")

    approved = Purchase.objects.filter(approval_status="approved")
    approved.update(delivery_status="received")
    PurchaseItem.objects.filter(purchase__in=approved).update(
        quantity_received=models.F("quantity")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0024_purchase_actual_delivery_date_alter_supplier_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Awaiting Delivery'), ('partial', 'Partially Received'), ('received', 'Fully Received')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            mark_approved_purchases_received, migrations.RunPython.noop
        ),
    ]
