# Generated by Django 5.2.6 on 2025-10-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0024_alter_prescriptioncartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptioncartitem',
            name='quantity_dispensed',
            field=models.IntegerField(
                default=0,
                help_text='Quantity already dispensed from this cart item'
            ),
        ),
    ]
