# Generated by Django 5.2.6 on 2025-10-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0025_fix_quantity_dispensed_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity to dispense (managed at cart level)'),
        ),
    ]
