# Generated by Django 5.2.6 on 2025-10-09 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0026_prescription_item_quantity_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterDispensaryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inter_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_dispensary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_inter_transfers', to='pharmacy.dispensary')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_dispensary_transfers', to='pharmacy.medication')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_inter_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_dispensary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_inter_transfers', to='pharmacy.dispensary')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_inter_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inter-Dispensary Transfer',
                'verbose_name_plural': 'Inter-Dispensary Transfers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='pharmacy_in_status_80d5b5_idx'), models.Index(fields=['from_dispensary', 'status'], name='pharmacy_in_from_di_fb67de_idx'), models.Index(fields=['to_dispensary', 'status'], name='pharmacy_in_to_disp_eb9a6c_idx'), models.Index(fields=['medication', 'status'], name='pharmacy_in_medicat_89cd37_idx')],
            },
        ),
    ]
