# Generated by Django 5.1.5 on 2025-10-28 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_payment_options_payment_idx_payment_date_and_more'),
        ('consultations', '0010_remove_consultation_consultation_type_and_more'),
        ('nhia', '0002_authorizationcode'),
        ('patients', '0012_physiotherapyrequest'),
        ('pharmacy', '0027_interdispensarytransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-prescription_date', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient'], name='idx_presc_patient'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor'], name='idx_presc_doctor'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='idx_presc_status'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_date'], name='idx_presc_date'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['payment_status'], name='idx_presc_payment'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['authorization_status'], name='idx_presc_auth'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['created_at'], name='idx_presc_created'),
        ),
    ]
