# Generated by Django 4.2.26 on 2026-06-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0028_fold_legacy_inventory_into_active_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicationInventory',
        ),
    ]
