# Generated by Django 5.1.5 on 2025-11-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0029_make_doctor_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='priority_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='submitted_for_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
