# Generated by Django 4.2.26 on 2026-06-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('pharmacy', '0029_delete_medicationinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='activestore',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='activestorebatch',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='activestoreinventory',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='bulkstore',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='bulkstoreinventory',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='dispensary',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='dispensarytransfer',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='dispensinglog',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='interdispensarytransfer',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='medicalpack',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='medicalpackitem',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='medication',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='medicationcategory',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='medicationtransfer',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='pack',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='packitem',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='packorder',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='pharmacistdispensaryassignment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='pharmacyexpense',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='purchaseapproval',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
    ]
