# Generated by Django 5.1.5 on 2025-11-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0030_purchase_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_purchases', 'Can approve purchase orders'), ('can_process_payments', 'Can process purchase payments')]},
        ),
    ]
