# Generated by Django 4.2.26 on 2026-07-08 17:43

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0031_prescriptioncart_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[core.validators.validate_nigerian_phone]),
        ),
    ]
