# Generated by Django 5.1.5 on 2025-11-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0031_add_purchase_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
