# Generated by Django 4.2.26 on 2026-07-08 17:45

import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0032_alter_supplier_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=core.validators.NigerianPhoneField(max_length=15),
        ),
    ]
