# Generated by Django 4.2.26 on 2026-07-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0033_alter_supplier_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispensary',
            options={'ordering': ['name'], 'permissions': [('manage_pharmacists', 'Can manage pharmacist assignments to dispensary')], 'verbose_name_plural': 'Dispensaries'},
        ),
    ]
