# Generated by Django 4.2.7 on 2025-11-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0034_add_delivered_status_to_transfer'),
    ]

    operations = [
    ]
