# Generated by Django 4.2.26 on 2026-07-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0034_alter_dispensary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-prescription_date', '-created_at'], 'permissions': [('dispense_medication', 'Can dispense medications to patients')]},
        ),
    ]
