# Generated by Django 4.2.26 on 2026-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_hospital_address_hospital_email_hospital_phone'),
        ('pharmacy', '0035_alter_prescription_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkstore',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dispensary',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bulkstore',
            unique_together={('hospital', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='dispensary',
            unique_together={('hospital', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('hospital', 'invoice_number')},
        ),
        migrations.AddConstraint(
            model_name='bulkstore',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', True)), fields=('name',), name='uniq_bulkstore_name_when_no_hospital'),
        ),
        migrations.AddConstraint(
            model_name='dispensary',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', True)), fields=('name',), name='uniq_dispensary_name_when_no_hospital'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', True)), fields=('invoice_number',), name='uniq_purchase_invoice_number_when_no_hospital'),
        ),
    ]
