# Generated by Django 5.2.3 on 2025-06-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuserprofile_updated_at_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
    ]
