# Generated by Django 5.2.3 on 2025-06-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuserprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
