# Generated by Django 5.2.6 on 2025-10-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_activity_monitoring_models'),
        ('accounts', '0013_alter_customuserprofile_user'),
    ]

    operations = [
    ]
