# Generated by Django 5.1.5 on 2025-10-25 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_missing_fields_to_activity_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityalert',
            options={'ordering': ['-created_at', '-severity'], 'verbose_name': 'Activity Alert', 'verbose_name_plural': 'Activity Alerts'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
        migrations.AlterField(
            model_name='activityalert',
            name='alert_type',
            field=models.CharField(choices=[('multiple_failed_logins', 'Multiple Failed Logins'), ('unusual_access_time', 'Unusual Access Time'), ('suspicious_ip', 'Suspicious IP Address'), ('privilege_escalation', 'Privilege Escalation'), ('bulk_operations', 'Bulk Operations'), ('high_frequency_requests', 'High Frequency Requests'), ('unauthorized_access', 'Unauthorized Access'), ('system_error', 'System Error'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activityalert',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='activityalert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
