# Generated by Django 4.2.7 on 2025-10-27 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_activityalert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to this role', related_name='customuser_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
