# Generated by Django 4.2.7 on 2025-11-14 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_role_users_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='DEPRECATED: Use CustomUser.is_active instead'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='DEPRECATED: Use CustomUser.phone_number instead', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiology_staff', 'Radiology Staff'), ('accountant', 'Accountant'), ('health_record_officer', 'Health Record Officer')], help_text='DEPRECATED: Use CustomUser.roles (ManyToMany) instead', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to this role', related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
