# Generated by Django 4.2.7 on 2025-11-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuserprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
    ]
