# Generated by Django 4.2.26 on 2026-01-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_role_users_alter_customuserprofile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
    ]
