# Generated by Django 4.2.26 on 2026-02-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_role_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiology_staff', 'Radiology Staff'), ('accountant', 'Accountant'), ('health_record_officer', 'Health Record Officer'), ('desk_officer', 'Desk Officer')], max_length=30, null=True),
        ),
    ]
