# Generated by Django 4.2.26 on 2026-02-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_customuserprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='accounts.department', verbose_name='assigned departments'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='accounts.department', verbose_name='primary department'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiology_staff', 'Radiology Staff'), ('accountant', 'Accountant'), ('health_record_officer', 'Health Record Officer'), ('desk_officer', 'Desk Officer'), ('cashier_accountant', 'Cashier/Accountant')], max_length=30, null=True),
        ),
    ]
