# Generated by Django 4.2.26 on 2026-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_customuserprofile_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='joining_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
