# Generated by Django 4.2.26 on 2026-06-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('accounts', '0026_seed_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital this staff belongs to. Null = platform-level user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='saas.hospital'),
        ),
    ]
