# Generated by Django 4.2.26 on 2026-06-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('accounts', '0028_department_hospital_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityalert',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
    ]
