# Generated by Django 4.2.26 on 2026-07-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_activityalert_hospital_auditlog_hospital_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', True)), fields=('name',), name='uniq_department_name_when_no_hospital'),
        ),
    ]
