# Generated by Django 4.2.26 on 2026-07-06 07:40

from collections import defaultdict

from django.db import migrations, models


def dedupe_null_hospital_departments(apps, schema_editor):
    """Merge duplicate tenant-less (hospital IS NULL) departments before the
    partial unique constraint is added.

    unique_together(hospital, name) never guarded these rows because SQL treats
    NULL as distinct, so double-seeding could leave several rows with the same
    name and no hospital. For each such group we keep the lowest id, repoint
    every reference (FK, one-to-one and M2M) onto it, then delete the rest.
    """
    Department = apps.get_model('accounts', 'Department')
    db = schema_editor.connection.alias

    groups = defaultdict(list)
    for dept in Department.objects.using(db).filter(hospital__isnull=True).order_by('id'):
        groups[dept.name].append(dept)

    for name, rows in groups.items():
        if len(rows) < 2:
            continue
        survivor, doomed = rows[0], rows[1:]

        for rel in Department._meta.related_objects:
            field = rel.field
            related_model = rel.related_model

            if rel.many_to_many:
                through = field.remote_field.through
                # FK on the through table that points back at Department
                dept_col = next(
                    f.name for f in through._meta.fields
                    if f.is_relation and f.related_model == Department
                )
                # the "other side" FK, used to avoid creating duplicate pairs
                other_col = next(
                    f.name for f in through._meta.fields
                    if f.is_relation and f.related_model != Department and f.related_model is not None
                )
                for d in doomed:
                    for link in through.objects.using(db).filter(**{dept_col: d}):
                        other_id = getattr(link, other_col + '_id')
                        exists = through.objects.using(db).filter(
                            **{dept_col: survivor, other_col + '_id': other_id}
                        ).exists()
                        if exists:
                            link.delete()
                        else:
                            setattr(link, dept_col, survivor)
                            link.save(update_fields=[dept_col])
            else:
                for d in doomed:
                    related_model.objects.using(db).filter(
                        **{field.name: d}
                    ).update(**{field.name: survivor})

        for d in doomed:
            d.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_activityalert_hospital_auditlog_hospital_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_null_hospital_departments, noop),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', True)), fields=('name',), name='uniq_department_name_when_no_hospital'),
        ),
    ]
