# Generated by Django 4.2.26 on 2026-07-08 17:43

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_seed_popd_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[core.validators.validate_nigerian_phone]),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, validators=[core.validators.validate_nigerian_phone]),
        ),
    ]
