# Generated by Django 4.2.26 on 2026-07-08 17:45

import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=core.validators.NigerianPhoneField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='phone_number',
            field=core.validators.NigerianPhoneField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
    ]
