# Generated by Django 4.2.26 on 2026-07-13 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_enforce_annual_discount'),
        ('accounts', '0034_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Date when staff was assigned to this department')),
                ('end_date', models.DateTimeField(blank=True, help_text='Date when assignment ended', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='The department where the staff is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='accounts.department')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital')),
                ('staff', models.ForeignKey(help_text='The staff user', on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Department Assignment',
                'verbose_name_plural': 'Staff Department Assignments',
                'ordering': ['-start_date', 'department__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffdepartmentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('staff', 'department'), name='uniq_active_staff_department_assignment'),
        ),
    ]
