# Generated by Django 4.2.26 on 2026-07-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_staffdepartmentassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='unit',
            field=models.CharField(blank=True, db_index=True, help_text='Optional unit within the department. When set, department dashboards show only referrals sent to this unit.', max_length=100, null=True),
        ),
    ]
