# Generated by Django 4.2.26 on 2026-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_backfill_orphan_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('hospital', 'username'), name='uniq_username_per_hospital'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', True)), fields=('username',), name='uniq_username_when_no_hospital'),
        ),
    ]
