# Generated by Django 5.2.6 on 2025-09-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultationorder'),
        ('nhia', '0002_authorizationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='authorization_code',
            field=models.ForeignKey(blank=True, help_text='Authorization code from desk office for NHIA patient in non-NHIA room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='nhia.authorizationcode'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='authorization_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='not_required', help_text='Status of authorization for this consultation', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='requires_authorization',
            field=models.BooleanField(default=False, help_text='True if this NHIA patient consultation in non-NHIA room requires desk office authorization'),
        ),
        migrations.AddField(
            model_name='referral',
            name='authorization_code',
            field=models.ForeignKey(blank=True, help_text='Authorization code from desk office for NHIA patient referral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='nhia.authorizationcode'),
        ),
        migrations.AddField(
            model_name='referral',
            name='authorization_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='not_required', help_text='Status of authorization for this referral', max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='requires_authorization',
            field=models.BooleanField(default=False, help_text='True if this NHIA patient referral from NHIA to non-NHIA unit requires desk office authorization'),
        ),
    ]
