# Generated by Django 5.2.6 on 2025-10-01 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_authorization_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='consultation',
            field=models.ForeignKey(blank=True, help_text='Optional link to the consultation this referral was created from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='consultations.consultation'),
        ),
    ]
