# Generated by Django 5.2 on 2025-10-03 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuserprofile_user'),
        ('consultations', '0006_make_referral_consultation_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred_to',
        ),
        migrations.AddField(
            model_name='referral',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor who accepted and is handling this referral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(choices=[('department', 'Department'), ('specialty', 'Specialty'), ('unit', 'Unit'), ('doctor', 'Specific Doctor')], default='department', max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_to_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_referrals_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_to_specialty',
            field=models.CharField(blank=True, help_text='Specialty within the department', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_to_unit',
            field=models.CharField(blank=True, help_text='Specific unit within the department', max_length=100, null=True),
        ),
    ]
