# Generated by Django 5.2 on 2025-10-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_add_department_referral_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(choices=[('department', 'Department'), ('specialty', 'Specialty'), ('unit', 'Unit')], default='department', max_length=20),
        ),
    ]
