# Generated by Django 5.1.5 on 2025-10-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_add_consultation_status_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='consultation_type',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='start_time',
        ),
    ]
