# Generated by Django 4.2.26 on 2026-06-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_remove_consultation_consultation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(choices=[('department', 'Department'), ('specialty', 'Specialty'), ('unit', 'Unit'), ('theatre', 'Theatre (Surgery)')], default='department', max_length=20),
        ),
    ]
