# Generated by Django 4.2.26 on 2026-06-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0007_admission_authorization_code'),
        ('consultations', '0012_remove_soapnote_assessment_remove_soapnote_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred_to_ward',
            field=models.ForeignKey(blank=True, help_text='Target ward for ward referrals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to='inpatient.ward'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(choices=[('department', 'Department'), ('specialty', 'Specialty'), ('unit', 'Unit'), ('ward', 'Ward'), ('theatre', 'Theatre (Surgery)')], default='department', max_length=20),
        ),
    ]
