# Generated by Django 4.2.26 on 2026-06-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_servicepoint'),
        ('consultations', '0013_referral_referred_to_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='service_point',
            field=models.ForeignKey(blank=True, help_text='Reception/records point that routed this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routed_waiting_entries', to='core.servicepoint'),
        ),
    ]
