# Generated by Django 4.2.26 on 2026-07-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0015_consultation_hospital_consultationnote_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='clinic_type',
            field=models.CharField(blank=True, choices=[('', 'N/A (General)'), ('mopd', 'MOPD (Medical Outpatient)'), ('sopd', 'SOPD (Surgical Outpatient)')], default='', help_text='Outpatient clinic: Medical (MOPD) or Surgical (SOPD)', max_length=10),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='clinic_type',
            field=models.CharField(blank=True, choices=[('', 'N/A (General)'), ('mopd', 'MOPD (Medical Outpatient)'), ('sopd', 'SOPD (Surgical Outpatient)')], default='', help_text='Outpatient clinic: Medical (MOPD) or Surgical (SOPD)', max_length=10),
        ),
    ]
