# Generated by Django 4.2.26 on 2026-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_hospital_address_hospital_email_hospital_phone'),
        ('consultations', '0018_seed_popd_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingroom',
            name='room_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='consultingroom',
            unique_together={('hospital', 'room_number')},
        ),
        migrations.AddConstraint(
            model_name='consultingroom',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', True)), fields=('room_number',), name='uniq_consulting_room_number_when_no_hospital'),
        ),
    ]
