# Generated by Django 4.2.26 on 2026-06-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gynae_emergency', '0003_gynaeemergencyclinicalnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gynae_emergencyrecord',
            options={'ordering': ['-visit_date'], 'permissions': [('view_gynaeemergencyrecord', 'Can view gynae emergency records')], 'verbose_name': 'Gynae_emergency Record', 'verbose_name_plural': 'Gynae_emergency Records'},
        ),
    ]
