# Generated by Django 4.2.26 on 2026-01-30 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0016_alter_patient_blood_group'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('surgery_type', models.CharField(blank=True, max_length=100, null=True)),
                ('surgery_date', models.DateTimeField(blank=True, null=True)),
                ('procedure_code', models.CharField(blank=True, max_length=50, null=True)),
                ('preop_diagnosis', models.TextField(blank=True, help_text='Pre-operative diagnosis', null=True)),
                ('preop_assessment', models.TextField(blank=True, null=True)),
                ('anesthesia_type', models.CharField(blank=True, help_text='General, Spinal, Local, etc.', max_length=50, null=True)),
                ('operative_findings', models.TextField(blank=True, null=True)),
                ('procedure_performed', models.TextField(blank=True, null=True)),
                ('implants_used', models.TextField(blank=True, help_text='List of implants/prosthetics used', null=True)),
                ('complications', models.TextField(blank=True, null=True)),
                ('estimated_blood_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Blood loss in mL', max_digits=6, null=True)),
                ('postop_diagnosis', models.TextField(blank=True, null=True)),
                ('postop_instructions', models.TextField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True, null=True)),
                ('postop_day', models.IntegerField(blank=True, help_text='Post-operative day', null=True)),
                ('wound_status', models.CharField(blank=True, help_text='Clean, Infected, etc.', max_length=50, null=True)),
                ('pain_level', models.IntegerField(blank=True, help_text='Pain scale 1-10', null=True)),
                ('mobility_status', models.CharField(blank=True, max_length=50, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('authorization_code', models.CharField(blank=True, help_text='Authorization code from desk office', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anesthesiologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anesthesiologist_doctor', to='doctors.doctor')),
                ('assistant_surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_surgeon', to='doctors.doctor')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_doctor', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_records', to='patients.patient')),
                ('surgeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_surgeon', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Surgery Record',
                'verbose_name_plural': 'Surgery Records',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text="Patient's description of symptoms, concerns, and history")),
                ('objective', models.TextField(help_text='Observable findings, examination results, and measurements')),
                ('assessment', models.TextField(help_text='Clinical assessment, diagnosis, and interpretation')),
                ('plan', models.TextField(help_text='Treatment plan, interventions, and follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_clinical_notes_created', to=settings.AUTH_USER_MODEL)),
                ('surgery_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='surgery.surgeryrecord')),
            ],
            options={
                'verbose_name': 'Surgery Clinical Note',
                'verbose_name_plural': 'Surgery Clinical Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
