# Generated by Django 4.2.26 on 2026-06-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': [('view_billingreport', 'Can view billing reports'), ('view_dailycashreport', 'Can view daily cash reports'), ('view_financialreport', 'Can view financial reports'), ('view_revenuereport', 'Can view revenue reports')]},
        ),
    ]
