# Generated by Django 4.2.26 on 2026-06-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('reporting', '0002_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='report',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
    ]
