# Generated by Django 4.2.26 on 2026-01-30 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0016_alter_patient_blood_group'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_remove_role_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('triage_level', models.CharField(choices=[('resuscitation', 'Resuscitation (Immediate)'), ('emergency', 'Emergency (Within 10 min)'), ('urgent', 'Urgent (Within 30 min)'), ('less_urgent', 'Less Urgent (Within 1 hour)'), ('non_urgent', 'Non-Urgent (Within 2 hours)')], default='urgent', max_length=20)),
                ('triage_notes', models.TextField(blank=True, null=True)),
                ('mode_of_arrival', models.CharField(choices=[('ambulance', 'Ambulance'), ('private_vehicle', 'Private Vehicle'), ('walk_in', 'Walk-in'), ('police', 'Police'), ('other', 'Other')], default='walk_in', max_length=20)),
                ('brought_by', models.CharField(blank=True, help_text='Name of person who brought patient', max_length=100, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gcs_score', models.IntegerField(blank=True, help_text='Glasgow Coma Scale score', null=True)),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField(blank=True, null=True)),
                ('past_medical_history', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('general_appearance', models.TextField(blank=True, null=True)),
                ('physical_examination', models.TextField(blank=True, null=True)),
                ('primary_diagnosis', models.TextField(blank=True, null=True)),
                ('secondary_diagnosis', models.TextField(blank=True, null=True)),
                ('investigations_done', models.TextField(blank=True, null=True)),
                ('treatment_given', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('under_observation', 'Under Observation'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('died', 'Died')], default='waiting', max_length=20)),
                ('discharge_time', models.DateTimeField(blank=True, null=True)),
                ('discharge_diagnosis', models.TextField(blank=True, null=True)),
                ('discharge_medications', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_instructions', models.TextField(blank=True, null=True)),
                ('authorization_code', models.CharField(blank=True, help_text='Authorization code from desk office', max_length=50, null=True)),
                ('referral_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_records', to='patients.patient')),
                ('referred_to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
            ],
            options={
                'verbose_name': 'Emergency Record',
                'verbose_name_plural': 'Emergency Records',
                'ordering': ['-arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text="Patient's description of symptoms, concerns, and history")),
                ('objective', models.TextField(help_text='Observable findings, examination results, and measurements')),
                ('assessment', models.TextField(help_text='Clinical assessment, diagnosis, and interpretation')),
                ('plan', models.TextField(help_text='Treatment plan, interventions, and follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_clinical_notes_created', to=settings.AUTH_USER_MODEL)),
                ('emergency_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='emergency.emergencyrecord')),
            ],
            options={
                'verbose_name': 'Emergency Clinical Note',
                'verbose_name_plural': 'Emergency Clinical Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
