# Generated by Django 4.2.26 on 2026-01-30 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0016_alter_patient_blood_group'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrthopedicsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('injury_type', models.CharField(blank=True, help_text='Type of injury (e.g., Fracture, Dislocation, Sprain, Strain)', max_length=50, null=True)),
                ('affected_body_part', models.CharField(blank=True, help_text='Affected body part (e.g., Spine, Hip, Knee, Shoulder, Wrist, Ankle)', max_length=50, null=True)),
                ('fracture_type', models.CharField(blank=True, help_text='Type of fracture if applicable', max_length=50, null=True)),
                ('fracture_classification', models.CharField(blank=True, help_text='Fracture classification (e.g., Simple, Compound, Comminuted, Greenstick)', max_length=50, null=True)),
                ('pain_score', models.IntegerField(blank=True, help_text='Pain score (0-10 scale)', null=True)),
                ('range_of_motion', models.TextField(blank=True, help_text='Range of motion assessment', null=True)),
                ('neurovascular_status', models.TextField(blank=True, help_text='Neurovascular status assessment', null=True)),
                ('imaging_results', models.TextField(blank=True, help_text='Imaging results (X-ray, CT, MRI findings)', null=True)),
                ('procedure_done', models.TextField(blank=True, help_text='Procedure or surgery performed', null=True)),
                ('implant_used', models.CharField(blank=True, help_text='Implant or fixation device used', max_length=200, null=True)),
                ('rehabilitation_plan', models.TextField(blank=True, help_text='Rehabilitation and physiotherapy plan', null=True)),
                ('weight_bearing_status', models.CharField(blank=True, help_text='Weight bearing status (e.g., Non-weight bearing, Partial, Full)', max_length=50, null=True)),
                ('diagnosis', models.CharField(blank=True, help_text='Primary diagnosis', max_length=100, null=True)),
                ('treatment_plan', models.TextField(blank=True, help_text='Treatment plan and recommendations', null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('authorization_code', models.CharField(blank=True, help_text='Authorization code from desk office', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orthopedics_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Orthopedics Record',
                'verbose_name_plural': 'Orthopedics Records',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='OrthopedicsClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text="Patient's description of symptoms, concerns, and history")),
                ('objective', models.TextField(help_text='Observable findings, examination results, and measurements')),
                ('assessment', models.TextField(help_text='Clinical assessment, diagnosis, and interpretation')),
                ('plan', models.TextField(help_text='Treatment plan, interventions, and follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orthopedics_clinical_notes_created', to=settings.AUTH_USER_MODEL)),
                ('orthopedics_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='orthopedics.orthopedicsrecord')),
            ],
            options={
                'verbose_name': 'Orthopedics Clinical Note',
                'verbose_name_plural': 'Orthopedics Clinical Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
