# Generated by Django 4.2.26 on 2026-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_annual_plans_extend_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
