# Generated by Django 4.2.26 on 2026-08-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_hospital_address_hospital_email_hospital_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, upload_to='hospital_logos/'),
        ),
    ]
