# Generated by Django 5.1.5 on 2025-10-28 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('patients', '0012_physiotherapyrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='idx_appt_date'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient'], name='idx_appt_patient'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor'], name='idx_appt_doctor'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='idx_appt_status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='idx_appt_date_status'),
        ),
    ]
