# Generated by Django 4.2.26 on 2026-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_idx_appt_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
