# Generated by Django 4.2.26 on 2026-07-19 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_fold_appointment_time_into_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentfollowup',
            name='booked_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_from_follow_up', to='appointments.appointment'),
        ),
    ]
