# Generated by Django 4.2.26 on 2026-07-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhia', '0005_authorizationcode_hospital_nhiapatient_hospital'),
        ('appointments', '0008_appointmentfollowup_booked_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='authorization_code',
            field=models.ForeignKey(blank=True, help_text='Authorization code required for NHIA patients', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='nhia.authorizationcode'),
        ),
    ]
