# Generated by Django 4.2.26 on 2026-07-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0018_seed_popd_rooms'),
        ('accounts', '0039_flip_lab_role_parent'),
        ('appointments', '0009_appointment_authorization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consulting_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='consultations.consultingroom'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.department'),
        ),
    ]
