# Generated by Django 5.1.5 on 2025-08-15 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyresult',
            name='contrast_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='contrast_used',
            field=models.CharField(choices=[('none', 'No Contrast'), ('oral', 'Oral Contrast'), ('iv', 'IV Contrast'), ('both', 'Oral + IV Contrast'), ('other', 'Other')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='image_quality',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('adequate', 'Adequate'), ('poor', 'Poor'), ('non_diagnostic', 'Non-diagnostic')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='radiology_studies/'),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_radiology', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='radiology_reports/'),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='result_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='study_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='study_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete'), ('limited', 'Limited'), ('cancelled', 'Cancelled')], default='complete', max_length=20),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='study_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='technique',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_radiology', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
