# Generated by Django 5.2 on 2025-08-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhia', '0002_authorizationcode'),
        ('radiology', '0002_radiologyresult_contrast_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyorder',
            name='authorization_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to='nhia.authorizationcode'),
        ),
    ]
