# Generated by Django 5.2.6 on 2025-09-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_authorization_code_and_more'),
        ('radiology', '0003_radiologyorder_authorization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyorder',
            name='authorization_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='not_required', help_text='Status of authorization for this radiology order', max_length=20),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='consultation',
            field=models.ForeignKey(blank=True, help_text='Link to the consultation this radiology order was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='requires_authorization',
            field=models.BooleanField(default=False, help_text='True if this NHIA patient radiology order from non-NHIA consultation requires desk office authorization'),
        ),
    ]
