# Generated by Django 4.2.26 on 2026-06-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('radiology', '0006_seed_radiology_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologycategory',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='radiologytest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='saas.hospital'),
        ),
    ]
