# Generated by Django 4.2.26 on 2026-08-21 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0008_seed_radiology_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyresult',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='radiology_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'csv', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tif', 'tiff', 'webp', 'dcm', 'dicom'])]),
        ),
        migrations.AlterField(
            model_name='radiologyresult',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='radiology_studies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'csv', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tif', 'tiff', 'webp', 'dcm', 'dicom'])]),
        ),
        migrations.AlterField(
            model_name='radiologyresult',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='radiology_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'csv', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tif', 'tiff', 'webp', 'dcm', 'dicom'])]),
        ),
    ]
