# Generated by Django 4.2.26 on 2025-12-12 16:26

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0006_alter_invoiceitem_service'),
        ('patients', '0014_sharedwallet_remove_wallettransaction_wallet_and_more'),
        ('nhia', '0003_authorizationcode_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeurologyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(blank=True, choices=[('stroke', 'Stroke'), ('epilepsy', 'Epilepsy'), ('migraine', 'Migraine'), ('parkinsons', "Parkinson's Disease"), ('alzheimers', "Alzheimer's Disease"), ('ms', 'Multiple Sclerosis'), ('neuropathy', 'Neuropathy'), ('tbi', 'Traumatic Brain Injury'), ('other', 'Other Neurological Condition')], max_length=20, null=True)),
                ('diagnosis', models.TextField(help_text='Diagnosis or findings')),
                ('treatment_procedure', models.TextField(help_text='Treatment procedure performed')),
                ('treatment_status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_appointment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires_authorization', models.BooleanField(default=False, help_text='True if this NHIA patient neurology record requires desk office authorization')),
                ('authorization_status', models.CharField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='not_required', help_text='Status of authorization for this neurology record', max_length=20)),
                ('authorization_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neurology_records', to='nhia.authorizationcode')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neurology_record', to='billing.invoice')),
                ('neurologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neurology_treatments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neurology_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Neurology Record',
                'verbose_name_plural': 'Neurology Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeurologyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Neurology Service',
                'verbose_name_plural': 'Neurology Services',
            },
        ),
        migrations.CreateModel(
            name='NeurologyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('eeg', 'EEG (Electroencephalogram)'), ('emg', 'EMG (Electromyography)'), ('mri', 'MRI (Magnetic Resonance Imaging)'), ('ct', 'CT Scan'), ('lumber_puncture', 'Lumbar Puncture'), ('blood_test', 'Blood Test'), ('nerve_conduction', 'Nerve Conduction Study'), ('other', 'Other')], max_length=30)),
                ('results', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('neurology_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='neurology.neurologyrecord')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Neurology Test',
                'verbose_name_plural': 'Neurology Tests',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='neurologyrecord',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neurology_records', to='neurology.neurologyservice'),
        ),
        migrations.CreateModel(
            name='NeurologyPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('neurology_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='neurology.neurologyrecord')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Neurology Prescription',
                'verbose_name_plural': 'Neurology Prescriptions',
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='NeurologyClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text="Patient's description of symptoms, concerns, and history")),
                ('objective', models.TextField(help_text='Observable findings, examination results, and measurements')),
                ('assessment', models.TextField(help_text='Clinical assessment, diagnosis, and interpretation')),
                ('plan', models.TextField(help_text='Treatment plan, interventions, and follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neurology_clinical_notes_created', to=settings.AUTH_USER_MODEL)),
                ('neurology_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='neurology.neurologyrecord')),
            ],
            options={
                'verbose_name': 'Neurology Clinical Note',
                'verbose_name_plural': 'Neurology Clinical Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
