# Generated by Django 4.2.26 on 2026-01-30 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0016_alter_patient_blood_group'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardiologyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chest_pain_type', models.CharField(blank=True, help_text='Type of chest pain (e.g., Angina, Myocardial Infarction, Non-cardiac)', max_length=50, null=True)),
                ('ecg_findings', models.TextField(blank=True, help_text='ECG/EKG findings and interpretation', null=True)),
                ('echocardiogram_results', models.TextField(blank=True, help_text='Echocardiogram results and findings', null=True)),
                ('stress_test_results', models.TextField(blank=True, help_text='Stress test results and interpretation', null=True)),
                ('cardiac_enzymes', models.TextField(blank=True, help_text='Cardiac enzyme levels (Troponin, CK-MB, etc.)', null=True)),
                ('lipid_profile', models.TextField(blank=True, help_text='Lipid profile results (Total Cholesterol, HDL, LDL, Triglycerides)', null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, help_text='Systolic blood pressure in mmHg', null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, help_text='Diastolic blood pressure in mmHg', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in beats per minute', null=True)),
                ('rhythm', models.CharField(blank=True, help_text='Cardiac rhythm (e.g., Normal Sinus, Atrial Fibrillation, Bradycardia)', max_length=50, null=True)),
                ('ejection_fraction', models.DecimalField(blank=True, decimal_places=1, help_text='Ejection fraction percentage (e.g., 55.0)', max_digits=4, null=True)),
                ('diagnosis', models.CharField(blank=True, help_text='Primary diagnosis (e.g., Hypertension, Heart Failure, Arrhythmia, CAD)', max_length=100, null=True)),
                ('treatment_plan', models.TextField(blank=True, help_text='Treatment plan and recommendations', null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('authorization_code', models.CharField(blank=True, help_text='Authorization code from desk office', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardiology_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Cardiology Record',
                'verbose_name_plural': 'Cardiology Records',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='CardiologyClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text="Patient's description of symptoms, concerns, and history")),
                ('objective', models.TextField(help_text='Observable findings, examination results, and measurements')),
                ('assessment', models.TextField(help_text='Clinical assessment, diagnosis, and interpretation')),
                ('plan', models.TextField(help_text='Treatment plan, interventions, and follow-up')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cardiology_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='cardiology.cardiologyrecord')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cardiology_clinical_notes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cardiology Clinical Note',
                'verbose_name_plural': 'Cardiology Clinical Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
