# Generated by Django 4.2.26 on 2026-06-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiology', '0002_remove_cardiologyclinicalnote_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiologyrecord',
            name='ecg_axis',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Axis (-30° to +90°)'), ('lad', 'Left Axis Deviation'), ('rad', 'Right Axis Deviation'), ('extreme', 'Extreme Axis Deviation')], help_text='QRS electrical axis', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cardiologyrecord',
            name='ecg_interpretation',
            field=models.TextField(blank=True, help_text='Auto-generated ECG interpretation summary', null=True),
        ),
        migrations.AddField(
            model_name='cardiologyrecord',
            name='ecg_pr_interval',
            field=models.IntegerField(blank=True, help_text='PR interval in ms (normal 120-200)', null=True),
        ),
        migrations.AddField(
            model_name='cardiologyrecord',
            name='ecg_qrs_duration',
            field=models.IntegerField(blank=True, help_text='QRS duration in ms (normal < 120)', null=True),
        ),
        migrations.AddField(
            model_name='cardiologyrecord',
            name='ecg_qt_interval',
            field=models.IntegerField(blank=True, help_text='Measured QT interval in ms', null=True),
        ),
        migrations.AddField(
            model_name='cardiologyrecord',
            name='ecg_qtc_interval',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Corrected QT (Bazett), auto-calculated in ms', max_digits=6, null=True),
        ),
    ]
