# Generated by Django 4.2.26 on 2026-06-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retainership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retainershippatient',
            options={'permissions': [('add_insurancepolicy', 'Can create insurance policies'), ('change_insurancepolicy', 'Can edit insurance policies'), ('view_insurancepolicy', 'Can view insurance policies')], 'verbose_name': 'Retainership Patient', 'verbose_name_plural': 'Retainership Patients'},
        ),
    ]
