# Generated by Django 5.2 on 2025-07-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('nhia', 'NHIA')], default='regular', max_length=10),
        ),
    ]
