# Generated by Django 5.2 on 2025-07-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_patient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NHIAPatient',
            fields=[
            ],
            options={
                'verbose_name': 'NHIA Patient',
                'verbose_name_plural': 'NHIA Patients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('patients.patient',),
        ),
    ]
