# Generated by Django 5.1.5 on 2025-09-12 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0007_admission_authorization_code'),
        ('patients', '0007_alter_patient_options_remove_patient_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='inpatient.admission'),
        ),
    ]
