# Generated by Django 5.2.6 on 2025-10-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_add_admission_to_wallet_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('refund', 'Refund'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment'), ('admission_fee', 'Admission Fee'), ('daily_admission_charge', 'Daily Admission Charge'), ('outstanding_admission_recovery', 'Outstanding Admission Recovery'), ('lab_test_payment', 'Lab Test Payment'), ('pharmacy_payment', 'Pharmacy Payment'), ('consultation_fee', 'Consultation Fee'), ('procedure_fee', 'Procedure Fee'), ('insurance_claim', 'Insurance Claim'), ('discount_applied', 'Discount Applied'), ('penalty_fee', 'Penalty Fee'), ('reversal', 'Transaction Reversal'), ('bonus', 'Bonus Credit'), ('cashback', 'Cashback')], max_length=30),
        ),
    ]
