# Generated by Django 5.2 on 2025-10-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('nhia', 'NHIA'), ('private', 'Private Pay'), ('insurance', 'Private Insurance'), ('corporate', 'Corporate'), ('staff', 'Staff'), ('dependant', 'Dependant'), ('emergency', 'Emergency')], default='regular', max_length=15),
        ),
    ]
