# Generated by Django 4.2.7 on 2025-10-26 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0011_remove_patient_blood_group_clinicalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysiotherapyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='Primary diagnosis or condition requiring physiotherapy')),
                ('treatment_plan', models.TextField(help_text='Proposed physiotherapy treatment plan')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='Scheduled start date for treatment', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Expected end date for treatment', null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physiotherapy_requests', to='patients.patient')),
                ('physiotherapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_physiotherapy', to=settings.AUTH_USER_MODEL)),
                ('referring_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_physiotherapy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Physiotherapy Request',
                'verbose_name_plural': 'Physiotherapy Requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
