# Generated by Django 4.2.26 on 2025-12-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_vaccinationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(help_text='Name for this shared wallet', max_length=100)),
                ('wallet_type', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family'), ('corporate', 'Corporate'), ('retainership', 'Retainership')], default='individual', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('retainership_registration', models.CharField(blank=True, help_text='Retainership registration number if applicable', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Shared Wallet',
                'verbose_name_plural': 'Shared Wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='The patient this transaction is for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='patient_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='patients.patientwallet'),
        ),
        migrations.AddField(
            model_name='patientwallet',
            name='shared_wallet',
            field=models.ForeignKey(blank=True, help_text='Shared wallet if this patient is part of a shared wallet system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_wallets', to='patients.sharedwallet'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='shared_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='patients.sharedwallet'),
        ),
        migrations.CreateModel(
            name='WalletMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary member?')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_left', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_memberships', to='patients.patient')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='patients.sharedwallet')),
            ],
            options={
                'verbose_name': 'Wallet Membership',
                'verbose_name_plural': 'Wallet Memberships',
                'ordering': ['-date_joined'],
                'unique_together': {('wallet', 'patient')},
            },
        ),
    ]
