# Generated by Django 4.2.26 on 2025-12-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_sharedwallet_remove_wallettransaction_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+')], max_length=3, null=True),
        ),
    ]
