# Generated by Django 4.2.26 on 2025-12-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_patient_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
    ]
