# Generated by Django 4.2.26 on 2026-02-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_alter_patient_blood_group'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active', 'patient_type'], name='idx_patient_active_type'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_type', 'created_at'], name='idx_patient_type_created'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['patient_wallet', '-created_at'], name='patients_wa_patient_35e020_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['shared_wallet', '-created_at'], name='patients_wa_shared__0fd3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['patient', 'transaction_type'], name='patients_wa_patient_8d5532_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['created_at'], name='patients_wa_created_cfe208_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='patients_wa_status_9536a0_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type'], name='patients_wa_transac_cc7a1c_idx'),
        ),
    ]
