# Generated by Django 4.2.26 on 2026-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_patient_idx_patient_active_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
