# Generated by Django 4.2.26 on 2026-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_alter_medicalhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('nhia', 'NHIA'), ('private', 'Private Pay'), ('insurance', 'Private Insurance'), ('corporate', 'Corporate'), ('staff', 'Staff'), ('dependant', 'Dependant'), ('emergency', 'Emergency'), ('retainership', 'Retainership')], default='regular', max_length=15),
        ),
    ]
