# Generated by Django 4.2.26 on 2026-06-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_add_retainership_patient_type_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientwallet',
            options={'permissions': [('deposit_to_wallet', 'Can deposit to patient wallet'), ('refund_walletpayment', 'Can refund wallet payments'), ('withdraw_from_wallet', 'Can withdraw from patient wallet')], 'verbose_name': 'Patient Wallet', 'verbose_name_plural': 'Patient Wallets'},
        ),
    ]
