# Generated by Django 4.2.26 on 2026-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_alter_patientwallet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='differential_diagnosis',
            field=models.TextField(blank=True, default='', help_text='Other diagnoses under consideration'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='drug_history_allergies',
            field=models.TextField(blank=True, default='', help_text='Current medications and known allergies'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='family_social_history',
            field=models.TextField(blank=True, default='', help_text='Family illnesses and social circumstances'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='general_examination',
            field=models.TextField(blank=True, default='', help_text='General condition and vital signs'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='history_of_presenting_complaint',
            field=models.TextField(blank=True, default='', help_text='Detailed history of the presenting complaint'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='investigations',
            field=models.TextField(blank=True, default='', help_text='Investigations requested and results'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='management_plan',
            field=models.TextField(blank=True, default='', help_text='Treatment, interventions and follow-up'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='past_medical_surgical_history',
            field=models.TextField(blank=True, default='', help_text='Previous illnesses, admissions and surgeries'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='presenting_complaint',
            field=models.TextField(blank=True, default='', help_text='Main complaint(s) and duration'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='provisional_diagnosis',
            field=models.TextField(blank=True, default='', help_text='Most likely diagnosis'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='review_of_systems',
            field=models.TextField(blank=True, default='', help_text='Systematic enquiry across body systems'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Brief case summary'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='systemic_examination',
            field=models.TextField(blank=True, default='', help_text='System-by-system examination findings'),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Additional notes / remarks'),
        ),
    ]
