# Generated by Django 4.2.26 on 2026-06-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_servicepoint'),
        ('patients', '0021_clinicalnote_differential_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='service_point',
            field=models.ForeignKey(blank=True, help_text='Reception/records point where this patient was registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to='core.servicepoint'),
        ),
    ]
