# Generated by Django 4.2.26 on 2026-07-08 17:43

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_clinicalnote_hospital_medicalhistory_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validate_nigerian_phone]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[core.validators.validate_nigerian_phone]),
        ),
    ]
