# Generated by Django 4.2.26 on 2026-07-08 17:45

import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_alter_patient_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=core.validators.NigerianPhoneField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=core.validators.NigerianPhoneField(blank=True, max_length=15, null=True),
        ),
    ]
