# Generated by Django 4.2.26 on 2026-07-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_alter_patient_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lga',
            field=models.CharField(blank=True, help_text='Local Government Area', max_length=100, null=True, verbose_name='LGA'),
        ),
        migrations.AddField(
            model_name='patient',
            name='tribe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
