# Generated by Django 4.2.26 on 2026-07-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_staffdepartmentassignment_and_more'),
        ('patients', '0027_patient_lga_patient_tribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='clinic_type',
            field=models.CharField(blank=True, choices=[('', 'N/A (General)'), ('mopd', 'MOPD (Medical Outpatient)'), ('sopd', 'SOPD (Surgical Outpatient)'), ('popd', 'POPD (Pediatric Outpatient)')], default='', help_text='Outpatient clinic where the patient was seen', max_length=10),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department where the patient was seen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes', to='accounts.department'),
        ),
    ]
