# Generated by Django 4.2.26 on 2026-07-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_clinicalnote_clinic_type_clinicalnote_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientwallet',
            options={'permissions': [('deposit_to_wallet', 'Can deposit to patient wallet'), ('refund_walletpayment', 'Can refund wallet payments'), ('withdraw_from_wallet', 'Can withdraw from patient wallet'), ('manage_patientwallet', 'Can manage wallet operations (adjust balances, refunds)')], 'verbose_name': 'Patient Wallet', 'verbose_name_plural': 'Patient Wallets'},
        ),
    ]
