# Generated by Django 4.2.26 on 2026-08-21 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_alter_patientwallet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='id_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'csv', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'tif', 'tiff', 'webp'])]),
        ),
    ]
