# Generated by Django 4.2.26 on 2026-02-02 18:29

from django.db import migrations
from django.db.models import Q


def create_doctor_profiles(apps, schema_editor):
    """Create Doctor profiles for CustomUser with doctor role that lack profiles"""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    Doctor = apps.get_model('doctors', 'Doctor')
    Specialization = apps.get_model('doctors', 'Specialization')
    Department = apps.get_model('accounts', 'Department')

    # Get or create a default specialization and department
    spec, _ = Specialization.objects.get_or_create(
        name='General Medicine',
        defaults={'description': 'General Medicine'}
    )
    dept, _ = Department.objects.get_or_create(
        name='General Medicine',
        defaults={'description': 'General Medicine Department'}
    )

    # Find users with doctor role who don't have a doctor profile
    doctor_users = CustomUser.objects.filter(
        Q(profile__role='doctor') | Q(profile__specialization__icontains='doctor')
    ).exclude(doctor_profile__isnull=False)

    for user in doctor_users:
        # Generate unique license number
        license_num = f"MD{user.id:04d}{user.id:04d}"
        Doctor.objects.create(
            user=user,
            specialization=spec,
            department=dept,
            license_number=license_num,
            experience='3-5',
            qualification='MBBS, MD',
            bio='',
            consultation_fee=0,
            available_for_appointments=True
        )


def reverse_func(apps, schema_editor):
    """Remove auto-created doctor profiles (those with generic license numbers)"""
    Doctor = apps.get_model('doctors', 'Doctor')
    Doctor.objects.filter(license_number__startswith='MD').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_doctor_profiles, reverse_func),
    ]
