# Generated by Django 4.2.26 on 2026-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_populate_doctor_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorexperience',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Leave blank if currently working here', null=True),
        ),
        migrations.AlterField(
            model_name='doctorexperience',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='end_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='start_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
