# Generated by Django 4.2.26 on 2026-02-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0021_alter_bulkstoreinventory_purchase_date_and_more'),
        ('pharmacy_billing', '0004_alter_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pharmacy.prescription'),
        ),
    ]
