# Generated by Django 4.2.26 on 2026-06-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_billing', '0006_alter_invoice_prescription_related_name'),
        # Must run AFTER the data has been copied into billing and carts
        # repointed, otherwise the copy in pharmacy.0027 reads dropped tables.
        ('pharmacy', '0027_unify_pharmacy_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='service',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='received_by',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
